/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.9.0
*/
FusionCharts.register("module",["private","modules.renderer.js-gradientlegend",function(){function U(c,g,p){var n=c[0],m=c[1];c=c[2];n+=(g[0]-n)*p;m+=(g[1]-m)*p;g=c+(g[2]-c)*p;return{hex:(ra+(n<<16|m<<8|g).toString(16)).slice(-6),rgb:[n,m,g]}}function V(c,g){return c.maxvalue-g.maxvalue}function F(c){var g,p,n=c.colorRange||{},m=c.dataMin,z=c.dataMax,t=c.sortLegend||!1,k=c.mapByCategory||!1,x=c.defaultColor,b=c.numberFormatter,e=n.color;c=this.colorArr=[];var d,h,a;this.mapByCategory=k;"1"===n.mapbypercent&&
(this.mapbypercent=!0);if("1"===n.gradient&&!k){this.gradient=!0;p=Ba(ca(n.startcolor,n.mincolor,n.code));t=ha(Ba(ca(p,x,"CCCCCC")));k=this.scaleMin=H(n.startvalue,n.minvalue,this.mapbypercent?0:m);c.push({code:p,maxvalue:k,label:W(n.startlabel),codeRGB:ha(p)});if(e&&(g=e.length))for(m=0;m<g;m+=1)x=e[m],p=Ba(ca(x.color,x.code)),h=H(x.value,x.maxvalue),a=H(x.minvalue),h>k&&c.push({code:p,maxvalue:h,userminvalue:a,label:W(ca(x.label,x.displayvalue)),codeRGB:ha(p)});c.sort(V);g=c.length;for(m=1;m<g;m+=
1)x=c[m],p=x.maxvalue-k,0<p?(x.minvalue=k,x.range=p,k=x.maxvalue):(c.splice(m,1),--m,--g);2<=c.length&&(this.scaleMax=k,c[m-1].label=ca(n.endlabel,c[m-1].label,c[m-1].displayvalue));1===c.length&&(h=H(n.maxvalue,this.mapbypercent?100:z),c.push({minvalue:k,maxvalue:h,range:h-k,label:n.endlabel}),this.scaleMax=h,delete c[0].code);n=c[0];z=c[c.length-1];n.code&&z.code||(p=da(t),g=Ea((p[2]=0,p)),p=Ea((p[2]=100,p)),n.code||(n.codeRGB=g,n.code=sa(g)),z.code||(z.codeRGB=p,z.code=sa(p)));g=c.length;for(m=
1;m<g;m+=1)if(x=c[m],x.code){if(d)for(z=x,a=n.maxvalue,e=z.maxvalue-a;d<m;d+=1)t=c[d],p=U(n.codeRGB,z.codeRGB,(t.maxvalue-a)/e),t.code=p.hex,t.codeRGB=p.rgb;d=null;n=x}else d=d||m;if(void 0===this.scaleMin||void 0===this.scaleMax)this.noValidRange=!0}else if(e&&(g=e.length)){for(m=0;m<g;m+=1)x=e[m],p=ca(x.color,x.code),h=H(x.maxvalue),a=H(x.minvalue),d=ca(x.label,x.displayvalue,k?X:b.dataLabels(a)+" - "+b.dataLabels(h)),(p&&h>a||k&&d)&&c.push({code:p,maxvalue:h,minvalue:a,label:W(d),labelId:d.toLowerCase()});
c.length?t&&c.sort(V):this.noValidRange=!0}}function Y(c,g){return g?I(100*c)/100+"%":P(c,X).toString()}var oa=this,c=oa.hcLib,ta=oa.window,ta=/msie/i.test(ta.navigator.userAgent)&&!ta.opera,H=c.pluckNumber,ra=c.COLOR_BLACK,g=c.COLOR_GLASS,Ca=c.FC_CONFIG_STRING,va=c.graphics,Ea=va.HSBtoRGB,da=va.RGBtoHSB,sa=va.RGBtoHex,ha=va.HEXtoRGB,ia=c.COMMASTRING,X=c.BLANKSTRING,W=c.parseUnsafeString,ua=c.graphics.convertColor,ya=c.POSITION_TOP,ma=c.POSITION_MIDDLE,xa=c.POSITION_START,Fa=c.POSITION_END,wa=c.graphics.getDarkColor,
pa=c.graphics.getLightColor,ca=c.pluck,P=c.getValidValue,qa=c.toRaphaelColor,za=c.hasTouch,I=Math.round,R=Math.max,T=Math.min,Ga=Math.abs,Z,Ha,Aa,Ia="rgba(192,192,192,"+(ta?.002:1E-6)+")",Ba=function(c){return c&&c.replace(/^#?([a-f0-9]+)/ig,"$1")};F.prototype={getColorObj:function(c){var g=this.colorArr,p=this.gradient?1:0,n=g[p],m;if(this.mapByCategory){for(c=W(c).toLowerCase();n;){if(n.labelId===c)return{code:n.code,seriesIndex:p};p+=1;n=g[p]}return{outOfRange:!0}}if(this.gradient){if(this.scaleMin<=
c&&this.scaleMax>=c){for(;n&&n.maxvalue<c;)p+=1,n=g[p];c=(c-n.minvalue)/n.range;return{code:U(g[p-1].codeRGB,n.codeRGB,c).hex}}return{outOfRange:!0}}for(;n;){if(n.maxvalue>c&&n.minvalue<=c)return{code:n.code,seriesIndex:p};n.maxvalue===c&&(m=p);p+=1;n=g[p]}return(n=g[m])&&n.maxvalue===c?{code:n.code,seriesIndex:m}:{outOfRange:!0}}};F.prototype.constructor=F;c.colorRange=F;Z=c.configureGradientLegendOptions=function(c,g){var p=c.legend,n=g.chart;p.legendSliderBorderWidth=H(n.legendpointerborderthickness,
1);p.legendSliderBorderColor=ua(ca(n.legendpointerbordercolor,ra),H(n.legendpointerborderalpha,100));p.legendSliderWidth=H(n.legendpointerwidth,n.legendpointerswidth,12);p.legendSliderHeight=H(n.legendpointerheight,n.legendpointersheight,12);p.legendColorBoxBorderColor=p.borderColor;p.legendColorBoxBorderWidth=p.borderWidth;p.legendScaleColor=ua(ca(n.legendscalelinecolor,ra),H(n.legendscalelinealpha,100));p.legendScalePadding=H(n.legendscalepadding,4);p.legendScaleLineThickness=H(n.legendscalelinethickness,
1);p.legendScaleTickDistance=H(n.legendscaletickdistance,6);p.itemStyle.cursor="default";p.interActivity=H(n.interactivelegend,1)};c.placeGLegendBlockRight=function(c,g,p,n,m){this.configureLegendOptions(c,g.chart,!0,m,p);Z(c,g);m=this.snapLiterals||(this.snapLiterals={});var z=c[Ca],t=this.smartLabel||z.smartLabel,k=c.legend,x=c.chart.spacingRight,b,e,d=k.textPadding=2,h=2*d,a=k.title.padding,f=0,ga=0,l=2*k.padding;g=H(g.chart.legendpadding,7)+k.borderWidth/2+1;var y=c.colorRange||{},w=y.colorArr,
ja=y.mapbypercent,O=y.scaleMin,q=y.scaleMax-O,$=k.legendSliderWidth,M=k.legendSliderHeight/2;e=k.legendScalePadding;var s=k.legendScaleTickDistance,u=k.itemStyle||{};b=H(parseInt(u.lineHeight,10)||12);var v=.75*b,S=p-l,C,D,r=0,E,A,B,K,G,Q,J;n-=l;if(!y.noValidRange&&w&&1<(D=w.length)){--D;k.title.text!==X&&(t.setStyle(k.title.style),b=t.getSmartText(k.title.text,S,R(b,n/4)),k.title.text=b.text,f=b.width+l,n-=ga=b.height+a);t.setStyle(u);b=t.lineHeight;S-=s+e+$;k.colorBoxX=$;a=R(b,S/2);S=T(S-a-4,b);
E=R(b,n/2);C=n/4;s=w[0];s.scaleLabel=Y(s.maxvalue,ja);b=t.getSmartText(s.label,C,S);s.label=b.text;u=b.height;s.labelY=v-b.height/2;e=t.getSmartText(s.scaleLabel,a,E);s.scaleLabel=e.text;y=e.height/2;A=e.width;s.scaleLabelY=v-e.height/2;k.colorBoxY=R(y,b.width+h,M)+ga;s=J=w[D];s.scaleLabel=Y(s.maxvalue,ja);b=t.getSmartText(s.label,C,S);s.label=b.text;u=R(u,b.height);s.labelY=v-b.height/2;e=t.getSmartText(s.scaleLabel,a,E);s.scaleLabel=e.text;A=R(A,e.width);C=e.height/2;b=R(b.width+h,C,M);s.scaleLabelY=
v-e.height/2;k.colorBoxHeight=M=n-k.colorBoxY-b;E=M-C;B=M/q;G=T(M-r,E-y)-4;for(C=1;C<D;C+=1)s=w[C],K=(s.maxvalue-O)*B,b=t.getSmartText(s.label,2*T(K-r,M-K),S),s.label=b.text,u=R(u,b.height),s.labelY=v-b.height/2,b=b.width/2,s.scaleLabel=Y(s.maxvalue,ja),e=t.getSmartText(s.scaleLabel,a,2*T(K-y,E-K)),s.scaleLabel=e.text,A=R(A,e.width),Q=e.height/2,s.scaleLabelY=v-e.height/2,G=T(G,(K-R(Q+y,b+r)-4)*q/s.range),r=b+K,y=Q+K;G=R(T(G,(T(E-y,M-r)-4)*q/J.range,.3*n),0);k.colorBoxHeight-=G;k.colorBoxWidth=u&&
u+h||15;k.height=k.totalHeight=n+ga+l-G;k.width=(A&&A+d)+k.colorBoxWidth+$+k.legendScaleTickDistance+k.legendScalePadding+l;k.width<f&&(k.colorBoxX+=(f-k.width)/2,k.width=f);k.width>p&&(k.width=p);m.legendstartx=z.width-x-k.width;m.legendwidth=k.width;m.legendendx=m.legendstartx+m.legendwidth;m.legendheight=k.height;g+=k.width;c.chart.marginRight+=g;return g}k.enabled=!1;return 0};c.placeGLegendBlockBottom=function(c,g,p,n,m){this.configureLegendOptions(c,g.chart,!1,m,p);Z(c,g);m=this.snapLiterals||
(this.snapLiterals={});var z=c[Ca],t=this.smartLabel||z.smartLabel,k=c.legend,x=c.chart,b=x.spacingBottom,e=x.spacingLeft,x=x.spacingRight,d,h,a=k.textPadding=2,f=k.title.padding,ga=0,l=0,y=2*k.padding;g=H(g.chart.legendpadding,7)+k.borderWidth/2+1;var w=c.colorRange||{},ja=w.colorArr,O=w.mapbypercent,q=w.scaleMin,$=w.scaleMax-q,M=k.legendSliderWidth,s=k.legendSliderHeight,u=k.legendScalePadding,v=k.legendScaleTickDistance,S=k.itemStyle||{};d=H(parseInt(S.lineHeight,10)||12);var C=.75*d,D=n-y,r,E,
A,B,K=0,G,Q,J;p-=y;if(!w.noValidRange&&ja&&1<(E=ja.length)){--E;k.title.text!==X&&(t.setStyle(k.title.style),d=t.getSmartText(k.title.text,p,D/3),k.title.text=d.text,ga=d.width+y,D-=l=d.height+f);t.setStyle(S);d=t.lineHeight;D-=v+u+s;f=R(d,D/2);S=T(D-f-4,d);r=p/4;B=2*r;A=ja[0];A.scaleLabel=Y(A.maxvalue,O);d=t.getSmartText(A.label,r,S);A.label=d.text;D=d.height;A.labelY=C-d.height/2;h=t.getSmartText(A.scaleLabel,B,f);A.scaleLabel=h.text;u=h.width/2;v=h.height;A.code||(A.code=ca(k.minColor,"CCCCCC"));
k.colorBoxX=R(u,d.width+a,M);A=w=ja[E];A.scaleLabel=Y(A.maxvalue,O);d=t.getSmartText(A.label,r,S);A.label=d.text;D=R(D,d.height);A.labelY=C-d.height/2;h=t.getSmartText(A.scaleLabel,B,f);A.scaleLabel=h.text;v=R(v,h.height);A=h.width/2;d=R(d.width+a,A,M);k.colorBoxWidth=M=p-k.colorBoxX-d;B=M-A;G=M/$;J=T(M-K,B-u)-4;for(r=1;r<E;r+=1)A=ja[r],Q=(A.maxvalue-q)*G,d=t.getSmartText(A.label,2*T(Q-K,M-Q),S),A.label=d.text,D=R(D,d.height),A.labelY=C-d.height/2,d=d.width/2,A.scaleLabel=Y(A.maxvalue,O),h=t.getSmartText(A.scaleLabel,
2*T(Q-u,B-Q),f),A.scaleLabel=h.text,v=R(v,h.height),h=h.width/2,J=T(J,(Q-R(h+u,d+K)-4)*$/A.range),K=d+Q,u=h+Q;J=R(T(J,(T(B-u,M-K)-4)*$/w.range,.3*p),0);k.colorBoxWidth-=J;k.width=p+y-J;k.width<ga&&(k.colorBoxX+=(ga-k.width)/2,k.width=ga);k.colorBoxY=l+s;k.colorBoxHeight=D&&D+2*a||15;k.height=k.totalHeight=(v&&v+a)+k.colorBoxHeight+l+s+k.legendScaleTickDistance+k.legendScalePadding+y;k.height>n&&(k.height=n);m.legendstartx=e+.5*(z.width-e-x-k.width)+(k.x||0);m.legendwidth=k.width;m.legendendx=m.legendstartx+
m.legendwidth;m.legendstarty=z.height-b-k.height;m.legendheight=k.height;m.legendendy=m.legendstarty+m.legendheight;g+=k.height;c.chart.marginBottom+=g;return g}k.enabled=!1;return 0};Ha=function(){return{point:this}};Aa=function(c){return I(100*c)/100};c.rendererRoot.drawGradientLegendItem=function(c){var F=this,p=F.paper,n=F.options,m=F.canvasLeft,z=F.canvasTop,t=F.canvasWidth,k=F.canvasHeight,x=n.colorRange,b=n.chart.textDirection,e,d,h,a,f=n.legend,ga=H(f.padding,4),l=f.itemStyle,n=f.symbolStyle,
y=f.interActivity,w=c.elements;c=w.elementGroup.trackTooltip(!0);var ja="vertical"===f.layout,O,q,$,M,s,u,v=0,S=f.lighting3d,C=f.colorBoxWidth,D=f.colorBoxHeight,r=C,E=D,A={FCcolor:{color:X,alpha:X,angle:0,ratio:X}},B=A.FCcolor,K=f.colorBoxX+ga,G=f.colorBoxY+ga,Q,J,La=f.legendColorBoxBorderColor,Ma=f.legendColorBoxBorderWidth,Da=["M"],ea=f.legendScaleColor;u=f.legendScalePadding;var Z=f.legendScaleLineThickness,U=Z%2/2;d=f.legendScaleTickDistance;var T=f.legendSliderWidth,Y=f.legendSliderHeight;s=
E/2;a=r/2;var P=T/2,aa=Y/2,V,ba,W;J=0;var fa=pa("ABABAB",50),ga=wa("ABABAB",70),f=ua("ABABAB",100),ga=ua(ga,100),fa=ua(fa,100),ha,N={isFirst:!0},L={},na,ka,la,da;if(x&&(e=x.colorArr)&&1<(h=e.length)){N.toolText=na=$=x.scaleMin;L.toolText=ka=x=x.scaleMax;M=x-$;N.snapPX=L.snapPX=0;N.tooltipConstraint=L.tooltipConstraint="chart";N.getLabelConfig=L.getLabelConfig=Ha;N.tooltipPos=[0,0];L.tooltipPos=[0,0];L.tooltipOffsetReference=N.tooltipOffsetReference={};L.tooltipOffsetReference.left=N.tooltipOffsetReference.left+=
m-20;L.tooltipOffsetReference.top=N.tooltipOffsetReference.top+=z;la=w.colorBox=p.group("colorBox",c);if(ja){N.tooltipPos[0]=L.tooltipPos[0]=t+m;J=270;B.angle=90;m=K-T;t=K+r;z=G-aa;O=G+aa;m=I(K-T)+.5;t=I(K)+.5;z=I(G-aa)+.5;O=I(G+aa)+.5;V=I(K+r)+.5;W=I(G-2)+.5;q=I(G+2)+.5;Q=I(G)+.5;k=K-P/2;ba=I(k-aa)+.5;k=I(k)+.5;s=G-aa/2;aa=I(s+aa)+.5;s=I(s)+.5;C/=2;P=["M",m,z,"L",t,z,t,W,V,Q,t,q,t,O,m,O,"Z","M",ba,s,"L",k,s,"M",ba,Q,"L",k,Q,"M",ba,aa,"L",k,aa];aa=["M",m+1,z,"L",m+1,O,"M",ba,s-1,"L",k,s-1,"M",ba,
Q-1,"L",k,Q-1,"M",ba,aa-1,"L",k,aa-1];s=K+r+u;O=I(s+d)+U;s=I(s)+U;Q=K+a;ba=h-1;for(d=0;d<h;d+=1)a=e[d],t=(a.maxvalue-$)/M,q=E*t+G,u=I(q)+U,d?(B.ratio+=ia,B.color+=ia,B.alpha+=ia,Da.push("L",s,u,O,u,"M",s,u),d===ba?(k=Fa,u=q+2):(k=ma,u=q)):(Da.push(s,u,"L",O,u,"M",s,u),k=xa,u=q-2),B.ratio+=100*(t-v),B.color+=ca(a.code,ra),B.alpha+=ca(a.alpha,100),v=t,a.legendItem=p.text(c).attr({text:a.label,x:Q,y:u,"text-anchor":k,direction:b,"vertical-align":ma}).rotate(J,Q,u).css(l),a.legendSymbol=p.text(c).attr({text:a.scaleLabel,
x:O,y:q,"text-anchor":xa,direction:b,"vertical-align":ma}).css(l);N.xMin=L.xMin=0;N.xMax=L.xMax=0;N.yMin=L.yMin=0;N.yMax=L.yMax=E;N.x=L.x=0;N.y=0;L.y=E;b=Y+r;e=T}else{N.tooltipPos[1]=L.tooltipPos[1]=k+z;m=I(K-P)+.5;t=I(K+P)+.5;z=I(G-Y)+.5;O=I(G+E)+.5;V=I(K-2)+.5;k=I(K+2)+.5;ba=I(K)+.5;W=I(G)+.5;q=G-aa/2;Q=I(q-aa)+.5;q=I(q)+.5;J=K-P/2;a=I(J+P)+.5;J=I(J)+.5;D/=2;P=["M",m,z,"L",t,z,t,W,k,W,ba,O,V,W,m,W,"Z","M",J,Q,"L",J,q,"M",ba,Q,"L",ba,q,"M",a,Q,"L",a,q];aa=["M",m,z+1,"L",t,z+1,"M",J-1,Q,"L",J-1,q,
"M",ba-1,Q,"L",ba-1,q,"M",a-1,Q,"L",a-1,q];u=G+E+u;J=I(u+d)+U;u=I(u)+U;q=G+s;ba=h-1;for(d=0;d<h;d+=1)a=e[d],t=(a.maxvalue-$)/M,O=r*t+K,s=I(O)+U,d?(B.ratio+=ia,B.color+=ia,B.alpha+=ia,Da.push("L",s,u,s,J,"M",s,u),d===ba?(k=xa,s=O+2):(k=ma,s=O)):(Da.push(s,u,"L",s,J,"M",s,u),k=Fa,s=O-2),B.ratio+=100*(t-v),B.color+=ca(a.code,ra),B.alpha+=ca(a.alpha,100),v=t,a.legendItem=p.text(c).attr({text:a.label,x:s,y:q,"text-anchor":k,direction:b,"vertical-align":ma}).css(l),a.legendSymbol=p.text(c).attr({text:a.scaleLabel,
x:O,y:J,"text-anchor":ma,direction:b,"vertical-align":ya}).css(l);N.xMin=L.xMin=0;N.xMax=L.xMax=r;N.yMin=L.yMin=0;N.yMax=L.yMax=0;N.y=L.y=0;N.x=0;L.x=r;b=T;e=Y+E}w.colorBox=p.rect(la).attr({x:K,y:G,width:r,height:E,fill:qa(A),stroke:La,strokeWidth:Ma});S&&(w.colorBoxEffect=p.rect(la).attr({x:K,y:G,width:C,height:D,fill:g,"stroke-width":0}));w.scale=p.path(c).attr({path:Da,stroke:ea,"stroke-width":Z});ha=function(a,b,e,d,c){var f;ja?(f=b*M/E+$,d=0<b?d:d+b+.01):(f=a*M/r+$,e=0<a?e:e+a+.01);a=Aa(f);c?
(w.slider1.translate(e,d),w.slider1Effect.translate(e,d),w.slider1Tracker.toFront().translate(e,d).tooltip(a,null,null,!0),na=f):(w.slider2.translate(e,d),w.slider2Effect.translate(e,d),w.slider2Tracker.toFront().translate(e,d).tooltip(a,null,null,!0),ka=f);y&&(da=clearTimeout(da),da=setTimeout(function(){F.setScaleRange&&F.setScaleRange(na,ka)},100))};h=function(a,b){var e=0,d=e,c,f=this.isFirst,h=f?L:N;if(ja){d=this._startY+b;0>=d&&(d=0);d>E&&(d=E);if(f?d>h.y:d<h.y)d=h.y;Ga(d-this.y)>=(this.snapPX||
0)&&(c=!0)}else{e=this._startX+a;0>=e&&(e=0);e>r&&(e=r);if(f?e>h.x:e<h.x)e=h.x;Ga(e-this.x)>=(this.snapPX||0)&&(c=!0)}c&&(ha(e,d,e-this.x,d-this.y,f),this.x=e,this.y=d)};S=function(){var a=this.isFirst;this._startX=this.x;this._startY=this.y;this._scaleStart=na;this._scaleEnd=ka;oa.raiseEvent("LegendPointerDragStart",{pointerIndex:a?0:1,pointers:[{value:na},{value:ka}],legendPointerHeight:Y,legendPointerWidth:T},F.logic.chartInstance)};C=function(){var a=this._scaleStart,b=this._scaleEnd;oa.raiseEvent("LegendPointerDragStop",
{pointerIndex:this.isFirst?0:1,pointers:[{value:na},{value:ka}],legendPointerHeight:Y,legendPointerWidth:T},F.logic.chartInstance);a===na&&b===ka||oa.raiseEvent("LegendRangeUpdated",{previousMinValue:a,previousMaxValue:b,minValue:na,maxValue:ka},F.logic.chartInstance);delete this._scaleStart;delete this._scaleEnd};D=Aa($);w.slider1=p.path(c).attr({path:P,fill:f,strokeWidth:1,stroke:ga});w.slider1Effect=p.path(c).attr({path:aa,fill:"none",strokeWidth:1,stroke:fa});za&&(m-=.5*(R(30,b)-b),z-=.5*(R(40,
e)-e),b=R(30,b),e=R(40,e));w.slider1Tracker=p.rect(c).attr({ishot:!0,width:b,height:e,x:m,y:z,fill:Ia,stroke:"none"}).drag(h,S,C,N,N,N).tooltip(D,null,null,!0).css(n);D=Aa(x);w.slider2=p.path(c).attr({path:P,fill:f,strokeWidth:1,stroke:ga}).translate(L.x,L.y);w.slider2Effect=p.path(c).attr({path:aa,fill:"none",strokeWidth:1,stroke:fa}).translate(L.x,L.y);w.slider2Tracker=p.rect(c).attr({ishot:!0,width:b,height:e,x:m,y:z,fill:Ia,stroke:"none"}).translate(L.x,L.y).css(n).drag(h,S,C,L,L,L).tooltip(D,
null,null,!0)}}}]);
FusionCharts.register("module",["private","modules.renderer.js-maps",function(){var U=this,V=U.window,F=U.hcLib,Y=F.chartAPI,oa=V.document,c=F.pluck,ta=F.imprint,H=F.extend2,ra=F.parseTooltext,g=F.pluckNumber,Ca=F.pluckFontSize,va=F.HCstub,Ea=H(F.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",backgroundlightalpha:"100",backgroundlightangle:90,
backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),da=F.setLineHeight,sa=F.getValidValue,ha=F.parseUnsafeString,ia=F.getFirstColor,X=F.graphics.convertColor,W=F.hashify,ua=F.getDashStyle,ya=V.navigator.userAgent,ma=/msie/i.test(ya)&&!V.opera,xa=/AppleWebKit/.test(ya),Fa=/stroke/ig,wa=F.hasSVG,pa=F.FC_CONFIG_STRING,ca=V.Math,P=ca.min,qa=ca.max,za=ca.ceil,ya=!/fusioncharts\.com$/i.test(V.location.hostname),
I=F.toRaphaelColor,R={left:"start",right:"end",center:"middle"},T=function(b,e){var d;b||(b={});for(d in e)b[d]=e[d];return b},Ga=function(b){var e=this.parentNode;if(!e)return!1;for(;e&&e!==oa.documentElement;){if(e===b)return!0;e=e.parentNode}return!1},Z=function(b,e){var d=e?T(b.FCcolor,e):{FCcolor:b};d.toString=I;return d},Ha=function(b,e){var d,c;this.index=e;for(c in b)d=Ea[b[c]],this[c]=d instanceof Array?d[e]:d},Aa={right:function(b,e){return e},left:function(b,e){return b-e},center:function(b,
e){return 2*P(e,b-e)}},Ia={top:function(b,e){return e},middle:function(b,e){return 2*P(e,b-e)},bottom:function(b,e){return b-e}},Ba=function(b,e,d,c){e=P(b,e);b=.02*e;e*=.07;c=parseFloat(c);d=parseFloat(d);return isNaN(c)||isNaN(d)?isNaN(c)?isNaN(d)?{min:b,max:e}:{min:parseInt(d/10,10),max:d}:{min:c,max:10*c}:c<d?{min:c,max:d}:{min:d,max:c}},Ka=function(b){for(var e=b&&b.length||0,d={},c;e--;)c=b[e],void 0!==c.id&&(d[c.id.toLowerCase()]=c);return d},Ja=function(b,e){var d,c={};e=e||1;if(!b||"object"!==
typeof b)return c;for(d in b)Fa.test(d)||("stroke-width"===d?(c[d]=Number(b[d])/e,xa&&(c[d]=c[d]&&za(c[d])||0)):c[d]=b[d]);return c},p=function(){this.hoverEntity&&(F.raiseEvent.apply(F,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null)},n=function(b,e){var c=b&&b.length||!1,h=e||"id",a={},f;if(!b)return b;for(;c--;)f=b[c],void 0!==f[h]&&(a[f[h].toLowerCase()]=
f);return a},m=function(b,e,c,h){function a(){var a=this,b=a.entityPathMap,e=a.data,c=a.items,d,e=Ka(e);u=function(){for(var h,g=b[d];g;)c[d]?a=null:((h=e[d])?h.mapItem=c[d]=new z(d,ta(f(h),g),q,a.group):c[d]=new z(d,g,q,a.group),d=g.nextId&&g.nextId.toLowerCase(),g=void 0!==d&&b[d]||null);k.call(a)};v=function(){var d,h,g=s,l,u=0;for(l in O)if(!c[l]&&(d=b[l],(h=e[l])?h.mapItem=c[l]=new z(l,ta(f(h),d),q,a.group):c[l]=new z(l,d,q,a.group),u+=1,delete O[l],u===g))break;u<n?(n-=u,setTimeout(v,0)):k.call(a)};
(d=w&&w.toLowerCase())?u():v()}function f(a){delete a.outlines;delete a.label;delete a.shortlabel;delete a.labelposition;delete a.labelalignment;delete a.labelconnectors;return a}function g(){var a=this.items,b=[],e,c={id:"entityLabels",items:b};for(e in a)a[e].drawLabel(b);m.addGroup(c)}function l(){var a=this.items,b;for(b in a)a[b].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group}function k(){M.entities.labelsOnTop&&g.call(this);this.ready=
!0;q.checkComplete()}if(c&&c.getEntityPaths()){var w=c.getFirstId(),n=c.entityCount,O=c.getEntityPaths(!0),q=e,m=e.mapAnnotations,M=q.options,s=wa?100:50,u,v,S;this.entityPathMap=O;this.data=b;this.chartObj=q;this.items={};this.ready=!1;this.group=h||e.mapGroup;this.isReady=function(){return this.ready};a.call(this);this.drawLabels=g;this.destroy=l;this.init=a;this.initComplete=k;q.__canvasMouseOutListenerAdded||(q.__canvasMouseOutListenerAdded=!0,S=e.paper.canvas,F.addEvent(S,"mouseout",function(a){a=
a.originalEvent.relatedTarget||a.originalEvent.toElement;!ma||wa?a&&a.ownerSVGElement&&a.ownerSVGElement===S||p.call(q):a===oa.documentElement||a===e.container||a===e.container.parentElement?p.call(q):Ga.call(a,S)||p.call(q)}))}},z=function(b,e,d,h){function a(a){var b=this.featureConfig;return b&&"undefined"!==typeof b[a]?Boolean(b[a]):!1}function f(){var b;if(a.apply(this,["_ds"])){b=e.labels&&e.labels[0];if(!b)return;b=(r.useSNameInTooltip?b.shortText:b.text)+(isNaN(A)?"":r.tooltipSepChar+B)}else b=
(r.useSNameInTooltip?e.shortLabel:e.label)+(isNaN(A)?"":r.tooltipSepChar+B);return b}function k(a,b,d){b?d&&"undefined"!==typeof e.displayvalue?a=e.displayvalue:(a=c(r.includeNameInLabels?r.useShortName?a.shortText:a.text:""),r.includeValueInLabels&&!isNaN(A)&&(a=void 0===a?B:a+K+B)):a=a.text;return a}function l(a){for(var b=a&&a.length||0,e;b--;)e=a[b],this.connectorElem[b]=D.path(e,this.group).attr({transform:la.transform,stroke:X(R,T),"shape-rendering":"crisp","stroke-width":P})}function y(){var a=
this.chart.paper,b=wa||!ma?"litepath":"path",e=this.eJSON.outlines,c=this.group,f,h,g;f=e&&e.length||0;if(this.hasFeature("_ds")){if(this.hasFeature("isDataEnabled"))if(L)for(;f--;)h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).attr(la).tooltip(t).shadow(ia,d.shadowLayer);else for(;f--;)h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(t).attr(la);else if(L)for(;f--;)g=H(H({},la),Ja(e[f].style,ka)),h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=
a[b](h,c).attr(g).tooltip(t).shadow(ia,d.shadowLayer);else for(;f--;)g=H(H({},la),Ja(e[f].style,ka)),h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(t).attr(g);this.hasFeature("isDataEnabled")&&this.addMouseGestures()}else{if(L)for(;f--;)h=e[f],this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).attr(la).tooltip(t).shadow(ia,d.shadowLayer);else for(;f--;)h=e[f],this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(t).attr(la);this.addMouseGestures()}return this}
function w(a){var b=this.chart;b.hoverEntityEventArgs=["entityrollout",this.eventArgs,b.fusionCharts,[b.fusionCharts.id,"rollOut",this.legacyEventArgs],a];da&&this.isVisible&&(b.hoverEntity=this,b.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr));F.raiseEvent("entityrollover",this.eventArgs,b.fusionCharts,[b.fusionCharts.id,"rollOver",this.legacyEventArgs],a)}function n(a,b,e){var c=this,f=c.chart,h=a.labelPosition,g=a.labelAlignment,l=c.svgElems[0]&&c.svgElems[0].graphic,u=a.style,r,v,q,
s,y;h?(l=h[0],h=h[1]):(h=l.getBBox(),l=h.x+h.width/2,h=h.y+h.height/2);g?(r=g[0],g=g[1],"right"===r?l-=V:"left"===r&&(l+=V),"top"===g?h-=V:"bottom"===g&&(h+=V)):(r="center",g="middle");v=aa;q=parseFloat(Y)/d.sFactor;s=W;y=oa;!b&&u&&(u.color&&(v=u.color),u["font-size"]&&(q=parseFloat(u["font-size"])/d.sFactor),u["font-family"]&&(s=u["font-family"]),void 0!==u["font-weight"]&&(y="bold"===u["font-weight"]));return{x:l.toString(),y:h.toString(),wrapwidth:Aa[r](sa,l+ua)-V,wrapheight:Ia[g](ta,h+va)-V,wrap:1,
type:"text",align:r,valign:g,text:k(a,b,e),tooltext:t,link:N,bgcolor:"",bordercolor:"",fillcolor:v,fontsize:q,font:s,bold:y,onclick:function(a){U.raiseEvent("entityclick",c.eventArgs,d.fusionCharts,a)},onmouseover:function(a){c!==f.hoverEntity&&(p.call(c.chart),w.call(c,a))},ontouchstart:function(a){c!==f.hoverEntity&&(p.call(c.chart),w.call(c,a))}}}function O(a){var b=this.eJSON,e=this.hasFeature("isDataEnabled"),c,d;if(!I)return null;if(this.hasFeature("_ds"))for(d=(b=b.labels)&&b.length||0;d--;)c=
b[d],a.push(this.getLabelObject(c,e,!d)),c.labelConnectors&&this.drawLabelConnectors(c.labelConnectors);else c={text:b.label,shortText:b.shortLabel,labelAlignment:b.labelAlignment,labelPosition:b.labelPosition},a.push(this.getLabelObject(c,!0,!0)),b.labelConnectors&&this.drawLabelConnectors(b.labelConnectors)}function q(a,b){var e=this.svgElems,c;for(c in e)e[c].graphic&&e[c].graphic.attr(a,b)}function m(){var a=this.svgElems,b;this.isVisible=!0;for(b in a)a[b].graphic&&a[b].graphic.attr(la)}function M(){var a=
this.svgElems,b=this.chart,e;this.isVisible=!1;b.hoverEntity===this&&p.call(b);for(e in a)a[e].graphic&&a[e].graphic.attr(na)}function s(a){U.raiseEvent("entityclick",this.node.__entity.eventArgs,d.fusionCharts,a);void 0!==N&&d.logic.linkClickFN.call({link:N})}function u(a){var b=this.node.__entity,e=b.chart;b!==e.hoverEntity&&(p.call(e),w.call(b,a))}function v(){var a=this.eJSON,b=this.svgElems,e;this.eventArgs={value:this.value,label:a.label,shortLabel:a.shortLabel,originalId:this.originalId||this.id,
id:this.id};this.legacyEventArgs={value:this.value,lName:a.label,sName:a.shortLabel,id:this.originalId||this.id};da&&(this.hoverAttr={fill:this.hoverColor.toString()},this.revertAttr={fill:this.fillColor.toString()},fa!==ea&&(this.hoverAttr["stroke-width"]=fa,this.revertAttr["stroke-width"]=ea));if(!isNaN(A)||ba)for(e in b)void 0!==N&&b[e].graphic.css({cursor:"pointer",_cursor:"hand"}),b[e].graphic.node.__entity=this,b[e].graphic.click(s).hover(u)}function S(){var a=this.svgElems,b=this.connectorElem,
e;for(e in a)a[e].remove&&a[e].remove();for(e in b)b[e].destroy&&b[e].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options}if(e&&d&&void 0!==b){this.chart=d;this.eJSON=e;this.group=h;this.id=b;this.originalId=e.origId;this.isVisible=!0;this.svgElems={};this.connectorElem=
{};this.featureConfig=e.options;"object"===typeof this.featureConfig&&(this.featureConfig._ds=!0);var C=d.options,D=d.paper,r=C.entities,E=r.dataLabels.style;b=e.cleanValue;var A=null===b?void 0:b,B=this.formattedValue=e.formattedValue||"",K=r.labelSepChar,G=g(e.showtooltip,r.showTooltip);b=f.call(this);h={formattedValue:B,sName:e.shortLabel,lName:e.label};var t=G?ha(c(ra(c(e.tooltext,r.tooltext,b),[1,2,7,38,39],h,e))):"",J,x,z,I=g(e.showlabel,r.showLabels);h=c(e.bordercolor,r.borderColor);b=c(e.borderalpha,
r.borderAlpha);var G=1===r.scaleBorder,ea=g(e.borderthickness,r.borderThickness),R=c(e.labelconnectorcolor,r.connectorColor),T=c(e.labelconnectoralpha,r.connectorAlpha),P=g(e.labelconnectorthickness,r.connectorThickness),W=c(e.font,E.fontFamily),Y=g(parseInt(e.fontsize,10),parseInt(E.fontSize,10)),aa=c(e.fontcolor,E.color),V=g(e.labelpadding,r.labelPadding),ba=r.hoverOnNull,da=g(e.showhovereffect,e.usehovercolor,ba?r.showHoverEffect:isNaN(A)?0:r.showHoverEffect),fa=g(e.borderhoverthickness,e.hoverborderthickness,
r.hoverBorderThickness),oa=g(e.fontbold,0),N=e.link,L=r.shadow;z=!ma||wa;E=d.sFactor/r.baseScaleFactor;J=d.strokeWidth;x=(z?r.baseScaleFactor:1)*J;var na=r.hiddenEntityFillObject||(r.hiddenEntityFillObject={fill:Z({color:r.hiddenEntityColor,alpha:r.hiddenEntityAlpha}).toString()}),ka,la,ia,C=C[pa],sa=C._labelBaseWidth,ta=C._labelBaseHeight,ua=C._labelXOffset,va=C._labelYOffset;z?(ea=G?ea*x:ea/E,P/=E,ka=G?E:d.sFactor,xa&&(ea=ea&&za(ea)||0,P=P&&za(P)||0)):(ea=G?ea*J:ea,ka=G?d.scaleFactor:r.baseScaleFactor);
r.showHiddenEntityBorder||(na["stroke-width"]=0);void 0===fa?fa=ea:z?(fa=G?ea*x:fa/E,xa&&(fa=fa&&za(fa)||0)):fa=G?fa*J:fa;!r.showNullEntityBorder&&isNaN(A)&&(ea=0);void 0!==c(e.color,e.alpha,e.angle,e.ratio)?(G=c(e.color,r.fillColor),C=c(e.alpha,r.fillAlpha),J=c(e.angle,r.fillAngle),x=c(e.ratio,r.fillRatio),z=Z({color:G,alpha:C,angle:J,ratio:x})):(r.fillColorObject||(r.fillColorObject=Z({color:c(r.fillColor),alpha:c(r.fillAlpha),angle:c(r.fillAngle),ratio:c(r.fillRatio)})),r.emptyColorObject||(r.emptyColorObject=
Z({color:c(r.nullEntityColor),alpha:c(r.nullEntityAlpha),angle:c(r.nullEntityAngle),ratio:c(r.nullEntityRatio)})),z=isNaN(A)?r.emptyColorObject:r.fillColorObject,G=z.FCcolor.color,C=z.FCcolor.alpha,J=z.FCcolor.angle,x=z.FCcolor.ratio);""===t&&(G=0);la={transform:wa||!ma?"":d.transformStr,stroke:X(h,b),"stroke-width":ea,fill:(this.fillColor=z).toString()};h=C.split(",");ea&&h.push(b);ia={scalefactor:[E,d.sFactor],opacity:qa.apply(ca,h)/100};da&&(void 0!==c(e.fillhovercolor,e.fillhoveralpha,e.fillhoverangle,
e.fillhoverratio,e.hoverfillcolor,e.hoverfillalpha,e.hoverfillratio,e.hoverfillangle)?(G=c(e.fillhovercolor,e.hoverfillcolor,r.hoverFillColor),C=c(e.fillhoveralpha,e.hoverfillalpha,r.hoverFillAlpha),J=c(e.fillhoverangle,e.hoverfillangle,r.hoverFillAngle),x=c(e.fillhoverratio,e.hoverfillratio,r.hoverFillRatio),b=Z({color:G,alpha:C,angle:J,ratio:x})):(r.hoverColorObject||(r.hoverColorObject=Z({color:r.hoverFillColor,alpha:r.hoverFillAlpha,angle:r.hoverFillAngle,ratio:r.hoverFillRatio})),b=r.hoverColorObject),
this.hoverColor=b);this.value=A;this.addMouseGestures=v;this.attr=q;this.draw=y;this.drawLabel=O;this.getLabelObject=n;this.destroy=S;this.show=m;this.hide=M;this.hasFeature=a;this.drawLabelConnectors=l;y.call(this);r.hideNullEntities&&void 0===A&&this.hide()}},t=function(b,e,c,h){this.id=b;this.definition=e;this.application=c;this.rapi=h;this.markerLabel=this.markerShape=this.label=this.options=this.value=this.hasValue=null;this.drawOptions={shape:null,label:null};this.drawComplete=!1;if(b=h.options)this._conf=
b[pa];this.init()},k=function(b,e,c,h){this.options=b;this.from=e;this.to=c;this.api=h;if(b=h.options)this._conf=b[pa]},x=function(b,e){function d(){var b=w.definition,c=n(b)||{},d=n(w.application)||{},h=w.shapes,g,l;if(b&&b.length){if(h&&h.length)for(b=h.length;b;--b)if(g=h[b-1],l=g.id.toLowerCase())a[l]=g;for(l in c){g=c[l];h=new t(l,g,d[l],e);if(b=h.getShapeId())h.shapeObj=a[b];f[l]=h}}}function h(){var b=w.items,c=w.shapes,d,h,g,l;if(b&&b.length){if(c&&c.length)for(d=c.length;d;--d)if(h=c[d-1],
l=h.id.toLowerCase())a[l]=h;for(d=b.length;d--;)if(h=b[d],l=h.id&&h.id.toLowerCase())void 0!==h.value&&""!==h.value&&parseFloat(h.value),h.mapItem=c=new t(l,h,null,e),g=c.getShapeId(),h.__hideMarker&&(c._isHidden=!0),g&&(c.shapeObj=a[g]),f[l]=c}}var a={},f={},g=[],l=e.options.markers,y=e.options.connectors,w=b,p=e.mapAnnotations,m,q,$,M,s=[];this.items=f;(function(){var a=t.prototype,b=k.prototype,d;d=Boolean(c(l.hoverFillColor,l.hoverFillAlpha,l.hoverFillAngle,l.hoverFillRatio,l.hoverBorderThickness,
l.hoverBorderColor,l.hoverBorderAlpha));a.markerFont=l.dataLabels.style.fontFamily;a.markerFontSize=l.dataLabels.style.fontSize;a.markerFontColor=l.dataLabels.style.fontColor;a.showMarkerTooltip=l.showTooltip;a.showHoverEffect=d;a.tooltext=l.tooltext;a.showMarkerLabels=l.showLabels;a.markerLabelPadding=l.labelPadding;a.labelWrapWidth=l.labelWrapWidth;a.labelWrapHeight=l.labelWrapHeight;a.labelSepChar=l.labelSepChar;a.tooltipSepChar=l.tooltipSepChar;a.fillColor=l.fillColor;a.fillAlpha=l.fillAlpha;
a.fillRatio=l.fillRatio;a.fillAngle=l.fillAngle;a.hoverFillColor=l.hoverFillColor;a.hoverFillAlpha=l.hoverFillAlpha;a.hoverFillRatio=l.hoverFillRatio;a.hoverFillAngle=l.hoverFillAngle;a.startAngle=l.startAngle;a.shapeId=l.shapeId;a.borderThickness=l.borderThickness;a.borderColor=l.borderColor;a.borderAlpha=l.borderAlpha;a.hoverBorderThickness=l.hoverBorderThickness;a.hoverBorderColor=l.hoverBorderColor;a.hoverBorderAlpha=l.hoverBorderAlpha;a.markerRadius=l.radius;a.autoScale=l.autoScale?e.sFactor:
1;a.shadow=l.shadow;a.applyAll=l.applyAll;a.dataEnabled=l.dataEnabled;a.valueToRadius=l.valueToRadius;a=Boolean(c(y.hoverthickness,y.hovercolor,y.hoveralpha));b.showHoverEffect=a;b.showTooltip=y.showTooltip;b.tooltext=y.tooltext;b.thickness=y.thickness;b.color=y.color;b.alpha=y.alpha;b.hoverThickness=y.hoverthickness;b.hoverColor=y.hovercolor;b.hoverAlpha=y.hoveralpha;b.dashed=y.dashed;b.dashlen=y.dashLen;b.dashgap=y.dashGap;b.font=y.font;b.fontsize=y.fontSize;b.fontcolor=y.fontColor;b.bgcolor=y.labelBgColor;
b.bordercolor=y.labelBorderColor;b.shadow=y.shadow;b.hideOpen=y.hideOpen})();l.dataEnabled?h():d();(function(){var b=f,e=[],c,d,h,g;q=p.addGroup({items:[]});m=p.addGroup({fillalpha:"100",items:e});for(g in b)c=null,d=b[g],h=d.getShapeId(),d&&!d._isHidden&&(h&&(d.shapeObj=a[h]),c=d.draw()),c&&(d._annotationIndex=e.length,d.markerShape=c.markerShape&&m.addItem(c.markerShape),d.markerLabel=c.markerLabel&&q.addItem(c.markerLabel))})();(function(){var a=y.showLabels,b=w.connectors,c=b&&b.length,d=[],h=
[],l,q,p;if(c)for(s.push({id:"connectorLabels",fillalpha:"100",items:h}),s.push({id:"connectors",fillalpha:"100",items:d});c--;)if(p=b[c],p.from&&p.to&&(l=f[p.from.toLowerCase()],q=f[p.to.toLowerCase()],l&&q&&(!y.hideOpen||!l._isHidden&&!q._isHidden)&&(g.push(q=new k(p,l,q,e)),q.connectJSON=l=q.computeConnectorJSON())))d.push(l),l.label&&a&&h.push(q.getLabelJSON())})();M=s.length;for(e.internalAnnotations={};M--;)$=s.shift(),$.id?e.internalAnnotations[$.id]=p.addGroup($):p.addGroup($);this.addMarkerItem=
function(b){var c,d;if((c=b.id.toLowerCase())&&!f[c]){delete b.value;b=new t(c,b,null,e);if(d=b.getShapeId())b.shapeObj=a[d];f[c]=b;c=b.draw();m&&q&&(b.markerShape=c.markerShape&&m.addItem(c.markerShape,!0),b.markerLabel=c.markerLabel&&q.addItem(c.markerLabel,!0))}}};k.prototype={constructor:k,computeConnectorJSON:function(){var b=this.api,e=this.options,d=this.from,h=this.to,a=e.link,f=e.label,k=g(e.showtooltip,this.showTooltip),l=k?c(e.tooltext,this.tooltext):"",y=c(e.thickness,this.thickness),
w=c(e.color,this.color),n=c(e.alpha,this.alpha),m=g(e.showhovereffect,this.showHoverEffect),q=c(e.hovercolor,this.hoverColor,w),t=c(e.hoveralpha,this.hoverAlpha,n),M=c(e.hoverthickness,this.hoverThickness,y),s=c(e.dashed,this.dashed),u=g(e.dashlen,this.dashlen),v=g(e.dashgap,this.dashgap),x;l&&(this.tooltext=l=ha(ra(l,[3,40,41,42,43],{label:f,fromId:d.definition.id,toId:h.definition.id,fromLabel:d.definition.label,toLabel:h.definition.label},e)));return d&&h?(x={fromMarkerId:d.id,toMarkerId:h.id,
label:f},H({type:"line"},{x:d.definition.x,y:d.definition.y,tox:h.definition.x,toy:h.definition.y,dashed:s,dashlen:u,dashgap:v,link:a,tooltext:k?l:"",thickness:y,color:w,alpha:n,label:f,showshadow:this.shadow,_hovereffect:m,_defaultattrs:{stroke:Z({color:w,alpha:n}).toString(),"stroke-width":y},_hoverattrs:{stroke:Z({color:q,alpha:t}).toString(),"stroke-width":M},onmouseover:function(a){var e=a.data,c=e.wrapper;c&&e.options._hovereffect&&(p.call(b),c.attr(e.options._hoverattrs));U.raiseEvent("connectorrollover",
x,b.fusionCharts,a)},onmouseout:function(a){var e=a.data,c=e.wrapper;c&&e.options._hovereffect&&c.attr(e.options._defaultattrs);U.raiseEvent("connectorrollout",x,b.fusionCharts,a)},onclick:function(a){U.raiseEvent("connectorClick",x,b.fusionCharts,a)}})):null},getLabelJSON:function(){var b=this.connectJSON;return H({type:"text"},{x:((Number(b.x)+Number(b.tox))/2).toString(),y:((Number(b.y)+Number(b.toy))/2).toString(),text:b.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize/
this.api.sFactor,fillcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};t.prototype={constructor:t,init:function(){var b;b=this.options=H({},this.definition);this.dataEnabled?isNaN(b.value)||""===b.value||(this.value=parseFloat(b.value),this.hasValue=!0):this.applyAll?this.options=H(b,this.application):this.application&&(this.options=H(b,this.application))},getShapeId:function(){return this.options.shapeid&&this.options.shapeid.toLowerCase()||this.shapeId},
getLabelOptions:function(b,e,c,h,a){var f,g=b&&b.toLowerCase();this.getLabelAlignment[g]||(g="center");b=Number(c.x);f=Number(c.y);c=void 0===h||void 0===a?c.radius||0:/^(top|bottom)$/ig.test(g)&&.5*a||/^(left|right)$/ig.test(g)&&.5*h||0;c=Number(c)+Number(e);return this.getLabelAlignment[g](b,f,c)},draw:function(){if(this.options){var b=this,e=b.rapi,d=b._conf,h=e.translateX,a=e.translateY,f=b.options,k=b.getShapeId(),l=f.scale||1,y=f.label||"",w=(f.labelpos||"top").toLowerCase(),n=void 0===f.formattedValue?
void 0:f.formattedValue,m=f.tooltext||b.tooltext,q=g(f.radius,b.markerRadius)*l*b.autoScale||1E-4,t=c(f.fillcolor,f.color,b.fillColor),M=c(f.fillalpha,f.alpha,b.fillAlpha),s=c(f.fillratio,b.fillRatio),u=c(f.fillangle,b.fillAngle),v=g(f.borderthickness,b.borderThickness),x=c(f.bordercolor,b.borderColor),C=c(f.borderalpha,b.borderAlpha),D=f.labelpadding||b.markerLabelPadding,r,E;if(k){m=m?ha(ra(m,[1,2,3],{formattedValue:n,label:y},f)):n?y+b.tooltipSepChar+n:y;void 0!==n&&null!==n?y=y+b.labelSepChar+
n:isNaN(l)?l=1:0>l?l=0:5<l&&(l=5);r=function(){var c=b.markerShape,d=c.options,f=c.bounds,g=d._markerEventArgs;(c=c.wrapper)&&d.hovereffect&&(p.call(e),c.attr(d._hoverattrs));g||(g=d._markerEventArgs={x:f.x1/f.xs,y:f.y1/f.ys,scaledX:f.x1,scaledY:f.y1,chartX:h+f.x1,chartY:a+f.y1,id:d._markerId,label:d._markerLabel});U.raiseEventGroup(b.id,"markerRollOver",g,e.fusionCharts,b,void 0,void 0,void 0)};E=function(){var a=b.markerShape,c=a.wrapper;c&&a.options.hovereffect&&c.attr(a.options._defaultattrs);
U.raiseEventGroup(b.id,"markerRollOut",a.options._markerEventArgs,e.fusionCharts,void 0,void 0,void 0)};f={x:f.x.toString(),y:f.y.toString(),fillcolor:t,fillalpha:M,fillratio:s,fillangle:u,borderthickness:v,bordercolor:x,borderalpha:C,hovereffect:c(f.showhovereffect,b.showHoverEffect),radius:q.toString(),tooltext:b.showMarkerTooltip?m:"",link:f.link,showshadow:g(f.showshadow,b.shadow),_markerLabel:y,_markerId:f.id,id:(f.id+"").toLowerCase(),onmouseover:function(){r()},onmouseout:function(){E()},onclick:function(a){U.raiseEvent("markerClick",
a.data.options._markerEventArgs,e.fusionCharts,a)}};"triangle"===k?H(f,{type:"polygon",sides:3,startangle:b.startAngle}):"diamond"===k?H(f,{type:"polygon",sides:4,startangle:b.startAngle}):"arc"===k?H(f,{type:"arc",startangle:0,endangle:360,innerradius:.6*q}):"circle"===k?f.type="circle":(D=b.getShapeArgs(),b.dataEnabled&&b.valueToRadius&&void 0!==f.radius?delete D.radius:(!D.radius&&(D.radius=b.markerRadius),D.radius=D.radius*l*b.autoScale),H(f,D));H(f,{hoverfillcolor:c(f.fillhovercolor,b.hoverFillColor,
f.fillcolor),hoverfillalpha:c(f.fillhoveralpha,b.hoverFillAlpha,f.fillalpha),hoverfillratio:c(f.fillhoverratio,b.hoverFillRatio,f.fillratio),hoverfillangle:c(f.fillhoverangle,b.hoverFillAngle,f.fillangle),hoverborderthickness:g(f.borderhoverthickness,b.hoverBorderThickness,f.borderthickness),hoverbordercolor:c(f.borderhovercolor,b.hoverBorderColor,f.bordercolor),hoverborderalpha:c(f.borderhoveralpha,b.hoverBorderAlpha,f.borderalpha)});f._defaultattrs={fill:Z({alpha:f.fillalpha,color:f.fillcolor,angle:f.fillangle,
ratio:f.fillratio}).toString(),"stroke-width":"0"!==f.showborder?f.borderthickness:0,stroke:X(f.bordercolor,f.borderalpha)};f._hoverattrs={fill:Z({alpha:f.hoverfillalpha,color:f.hoverfillcolor,angle:f.hoverfillangle,ratio:f.hoverfillratio}).toString(),"stroke-width":"0"!==f.showborder?f.hoverborderthickness:0,stroke:X(f.hoverbordercolor,f.hoverborderalpha)};"image"===f.type&&(f.borderthickness=f.borderthickness||0,f.onload=function(a){var b=this.options,c=a.width;a=a.height;var d=(Number(b.x)-c/(2*
e.sFactor))*e.sFactor,b=(Number(b.y)-a/(2*e.sFactor))*e.sFactor,f;if(c&&a)for(f in{wrapper:1,tracker:1})this[f]&&this[f].attr({x:d,y:b,width:c,height:a})});b.drawOptions.shape=f;if(!b.showMarkerLabels)return{markerShape:f};D=f.labelpadding||b.markerLabelPadding;l=b.getLabelOptions(w,D,f);w=l.align;k=l.valign;m=d._labelBaseWidth;n=d._labelBaseHeight;q=d._labelXOffset;d=d._labelYOffset;m=b.labelWrapWidth?b.labelWrapWidth:b.getWrapWidth[w](m,Number(l.x)+q);d=b.labelWrapHeight?b.labelWrapHeight:b.getWrapHeight[k](n,
Number(l.y)+d);m>D&&(m-=D);d>D&&(d-=D);b.drawOptions.label="center"==w&&"middle"==k?H({type:"text"},{text:y,tooltext:f.tooltext,x:l.x,y:l.y,align:w,valign:l.valign,wrap:1,wrapwidth:m,wrapheight:d,fontsize:b.markerFontSize/e.sFactor,font:b.markerFont,fillcolor:b.markerFontColor,onmouseover:function(){r()},onmouseout:function(){E()}}):H({type:"text"},{text:y,tooltext:f.tooltext,x:l.x,y:l.y,align:w,valign:l.valign,wrap:1,wrapwidth:m,wrapheight:d,fontsize:b.markerFontSize/e.sFactor,font:b.markerFont,
fillcolor:b.markerFontColor});return{markerShape:f,markerLabel:b.drawOptions.label}}}},show:function(){this.setMarkerVisibility(!0)},hide:function(){this.setMarkerVisibility(!1)},setMarkerVisibility:function(b){var e=this.rapi&&this.rapi.internalAnnotations;if(e=(e=e&&e.markers)&&e.items)if(e=e[this._annotationIndex])this._origFill||(this._origFill=Z({alpha:e.fillAlpha,color:e.fillColor,angle:e.fillAngle,ratio:e.fillRatio}),this._hideFill=Z({alpha:"0",color:e.fillColor,angle:e.fillAngle,ratio:e.fillRatio})),
b?e.wrapper.attr({fill:this._origFill}):e.wrapper.attr({fill:this._hideFill})},getShapeArgs:function(){var b=H({},this.shapeObj),e;return b?("polygon"===b.type?3>b.sides?b.type="circle":b.startangle=this.startAngle:"arc"===b.type&&(e=(b.radius||this.markerRadius)*this.autoScale,b.radius=e,b.innerradius=b.innerradius&&b.innerradius*this.autoScale||.6*e),b):null},destroy:function(){var b=this.markerShape,e=this.markerLabel,c;b&&b.destroy();e&&e.destroy();for(c in this)delete this[c]},getLabelAlignment:{top:function(b,
e,c){return{x:b.toString(),y:(e-c).toString(),align:"center",valign:"top"}},left:function(b,e,c){return{x:(b-c).toString(),y:e.toString(),align:"right",valign:"middle"}},right:function(b,e,c){return{x:(b+c).toString(),y:e.toString(),align:"left",valign:"middle"}},bottom:function(b,c,d){return{x:b.toString(),y:(c+d).toString(),align:"center",valign:"bottom"}},center:function(b,c){return{x:b.toString(),y:c.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(b,c){return c},left:function(b,
c){return b-c},center:function(b,c){return 2*P(c,b-c)}},getWrapHeight:{top:function(b,c){return c},middle:function(b,c){return 2*P(c,b-c)},bottom:function(b,c){return b-c}}};T(F.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});Y("geo",{name:"geo",friendlyName:"Map",revision:1,creditLabel:ya,standaloneInit:!1,annotationInteractionEvents:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",
rendererId:"maps",entities:{},draw:function(b,c){var d=this.renderer,h=this.chartInstance;d||(d=this.renderer=new Y("renderer."+this.rendererId));this.updateDefaultAnnotations();h.addEventListener("internal.mapdrawingcomplete",function(a,b){c&&c.apply(this,[b.renderer]);a.detachHandler()});return d.init(this,b,function(a){a.checkComplete()})},chart:function(b,e){H(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,
chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var d=this.dataObj,h=va(d,b,e,this),a=d.chart,f=d.markers,k=h.chart,l=h[pa],y=k.useRoundEdges=1===g(a.useroundedges),w=y?1:0,y=y?0:1,p=k.use3DLighting=1===g(a.use3dlighting,1),n=H({},h.tooltip.style),q=new Ha(this.colorPaletteMap,(0<a.palette&&6>a.palette?a.palette:g(this.paletteIndex,1))-1),m=c(a.basefont,"Verdana,sans"),t=Ca(a.basefontsize,10),s=c(a.basefontcolor,q.basefontcolor),u=Ca(a.outcnvbasefontsize,
t),v=c(a.outcnvbasefont,m),x=u+"px",C=W(c(a.outcnvbasefontcolor,s)),D=c(a.bgcolor,a.canvasbgcolor,q.canvasbgcolor),r=c(a.bgalpha,a.canvasbgalpha,q.canvasbgalpha),E=g(a.usevaluesformarkers,d.markers&&d.markers.items&&d.markers.items.length,!(d.markers&&d.markers.application&&d.markers.application.length&&d.markers.definition&&d.markers.definition.length)),A,B,K,G,z,J,I,t=t+"px",s=W(s);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,h);k.events.click=this.linkClickFN;
l.numberFormatter=this.numberFormatter;H(l,{width:b,height:e,showTooltip:g(a.showtooltip,this.showtooltip,1),showHoverEffect:g(a.showhovereffect,1),tooltipSepChar:c(a.tooltipsepchar,", "),showValues:g(a.showvalues,this.showValues,1),showCanvasBG:c(a.showcanvasbg,1),useValuesForMarkers:E,adjustViewPortForMarkers:g(a.adjustviewportformarkers,E),flatScrollBars:g(a.flatscrollbars,0),scrollBar3DLighting:g(a.scrollbar3dlighting,1),outCanvasStyle:{fontFamily:v,color:C,fontSize:x},inCanvasStyle:{fontFamily:m,
fontSize:t,color:s}});da(l.outCanvasStyle);A=da(l.inCanvasStyle);l.trendStyle=l.outCanvasStyle;"0"==l.showCanvasBG&&(r="0");B=c(a.entitybordercolor,a.bordercolor,q.plotbordercolor);K=c(a.entityfillcolor,a.fillcolor,q.plotfillcolor);G=c(a.entityfillalpha,a.fillalpha,q.plotfillalpha);z=c(a.entityfillratio,a.fillratio,q.plotfillratio);J=c(a.entityfillangle,a.fillangle,q.plotfillangle);I=c(a.nullentityfillcolor,a.nullentitycolor,K);E=g(a.showcanvasborder,y)?g(a.canvasborderthickness,1):0;H(h,{chart:{emulateFlashGutter:g(a._emulateflashgutter,
1),defaultSeriesType:this.defaultSeriesType,paletteIndex:q.index,borderRadius:g(a.canvasborderradius,0),borderColor:X(c(a.canvasbordercolor,q.canvasbordercolor),c(a.canvasborderalpha,q.canvasborderalpha)),borderWidth:E,borderDashStyle:g(a.canvasborderdashed,0)?ua(g(a.canvasborderdashlen,4),g(a.canvasborderdashgap,2),E):"none",backgroundColor:Z({color:D,alpha:r,angle:c(a.bgangle,a.canvasbgangle,q.canvasbgangle),ratio:c(a.bgratio,a.canvasbgratio,q.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,
plotBackgroundColor:Z({color:"#ffffff",alpha:0}),bgSWF:c(a.bgimage,a.bgswf),bgSWFAlpha:g(a.bgimagealpha,a.bgswfalpha,100),bgImageScale:g(a.bgimagescale,100),bgImageDisplayMode:c(a.bgimagedisplaymode,"none").toLowerCase(),logoURL:sa(a.logourl),logoPosition:c(a.logoposition,"tl").toLowerCase(),logoAlpha:g(a.logoalpha,100),logoLink:sa(a.logolink),logoScale:g(a.logoscale,100),logoLeftMargin:g(a.logoleftmargin,0),logoTopMargin:g(a.logotopmargin,0),toolbar:function(){var d={button:{}},f=d.button,h;f.scale=
g(a.toolbarbuttonscale,1.15);f.width=g(a.toolbarbuttonwidth,15);f.height=g(a.toolbarbuttonheight,15);f.radius=g(a.toolbarbuttonradius,2);f.spacing=g(a.toolbarbuttonspacing,5);f.fill=X(c(a.toolbarbuttoncolor,"ffffff"));f.labelFill=X(c(a.toolbarlabelcolor,"cccccc"));f.symbolFill=X(c(a.toolbarsymbolcolor,"ffffff"));f.hoverFill=X(c(a.toolbarbuttonhovercolor,"ffffff"));f.stroke=X(c(a.toolbarbuttonbordercolor,"bbbbbb"));f.symbolStroke=X(c(a.toolbarsymbolbordercolor,"9a9a9a"));f.strokeWidth=g(a.toolbarbuttonborderthickness,
1);f.symbolStrokeWidth=g(a.toolbarsymbolborderthickness,1);h=f.symbolPadding=g(a.toolbarsymbolpadding,5);f.symbolHPadding=g(a.toolbarsymbolhpadding,h);f.symbolVPadding=g(a.toolbarsymbolvpadding,h);h=d.position=c(a.toolbarposition,"tr").toLowerCase();switch(h){case "tr":case "tl":case "br":case "bl":break;default:h="tr"}f=d.hAlign="left"===(""+a.toolbarhalign).toLowerCase()?"l":h.charAt(1);h=d.vAlign="bottom"===(""+a.toolbarvalign).toLowerCase()?"b":h.charAt(0);d.hDirection=g(a.toolbarhdirection,"r"===
f?-1:1);d.vDirection=g(a.toolbarvdirection,"b"===h?-1:1);d.vMargin=g(a.toolbarvmargin,6);d.hMargin=g(a.toolbarhmargin,10);d.x=g(a.toolbarx,"l"===f?0:b);d.y=g(a.toolbary,"t"===h?0:e);return d}()},title:{text:ha(a.caption),offsetX:Number(a.captionxshift),offsetY:Number(a.captionyshift),position:c(a.captionposition,void 0!==a.captionxshift||void 0!==a.captionyshift?"top left":"top"),padding:g(a.captionpadding,10),style:{fontFamily:c(a.captionfontfamily,v),color:c(a.captionfontcolor,C).replace(/^#?([a-f0-9]+)/ig,
"#$1"),fontSize:g(a.captionfontsize,u+3)+"px",fontWeight:0===g(a.captionfontbold)?"normal":"bold"}},subtitle:{text:ha(a.subcaption),style:{fontFamily:c(a.subcaptionfontfamily,a.captionfontfamily,v),color:c(a.subcaptionfontcolor,a.captionfontcolor,C).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:g(a.subcaptionfontsize,g(qa(a.captionfontsize-3,1),u))+"px",fontWeight:0===g(a.subcaptionfontbold)?"normal":"bold"}},orphanStyles:{defaultStyle:{style:H({},l.inCanvasStyle)}},tooltip:{enabled:0!==l.showTooltip,
style:{fontFamily:m,fontSize:t,lineHeight:A,color:s,padding:g(a.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:X(c(n.backgroundColor,a.tooltipbgcolor,q.tooltipbgcolor),c(a.tooltipbgalpha,"100")),borderColor:X(c(n.borderColor,a.tooltipbordercolor,q.tooltipbordercolor),c(a.tooltipborderalpha,"100")),borderWidth:g(a.tooltipborderthickness,y)+"px",borderRadius:g(a.tooltipborderradius,w+1)+"px"},constrain:g(a.constraintooltip,1),shadow:g(a.showtooltipshadow,a.showshadow,1)?{enabled:!0,opacity:qa(g(a.tooltipbgalpha,
100),g(a.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:c(a.legenditemfont,v),fontSize:g(a.legenditemfontsize,u)+"px",color:W(c(a.legenditemfontcolor,C)),fontWeight:g(a.legenditemfontbold)?"bold":"normal"},itemHiddenStyle:{fontFamily:v,fontSize:x,color:W(c(a.legenditemhiddencolor,C))},itemHoverStyle:{color:W(c(a.legenditemhoverfontcolor,a.legenditemfontcolor,C))},enabled:g(a.showlegend,1),title:{text:ha(a.legendcaption),style:{fontFamily:c(a.legendcaptionfont,v),fontSize:g(a.legendcaptionfontsize,
u)+"px",color:W(c(a.legendcaptionfontcolor,C)),fontWeight:g(a.legendcaptionfontbold,1)?"bold":"normal"},align:R[c(a.legendcaptionalignment)]},position:c(a.legendposition,0===g(d.colorrange&&d.colorrange.gradient,0)?"right":"bottom"),backgroundColor:c(a.legendbgcolor,q.bgcolor),backgroundAlpha:c(a.legendbgalpha,"100"),borderColor:c(a.legendbordercolor,q.legendbordercolor),borderThickness:c(a.legendborderthickness,"1"),borderAlpha:c(a.legendborderalpha,"100"),shadow:g(a.legendshadow,1),allowDrag:g(a.legendallowdrag,
0),scroll:{scrollBgColor:c(a.legendscrollbgcolor,a.scrollcolor,"AAAAAA"),scrollBtnColor:c(a.legendscrollbtncolor,"BBBBBB"),scrollBarColor:c(a.legendscrollbarcolor,"CCCCCC")},reversed:g(a.reverselegend,0),interactive:g(a.interactivelegend,0),minColor:I,lighting3d:p},markers:{dataLabels:{style:{fontFamily:c(a.markerfont,m),fontSize:g(a.markerfontsize,parseInt(t,10)),fontColor:c(a.markerfontcolor,s)}},showTooltip:g(a.showmarkertooltip,l.showTooltip),showLabels:g(a.showmarkerlabels,a.showlabels,1),showHoverEffect:g(a.showmarkerhovereffect,
1),labelPadding:c(a.markerlabelpadding,"5"),labelWrapWidth:g(a.markerlabelwrapwidth,0),labelWrapHeight:g(a.markerlabelwrapheight,0),fillColor:c(a.markerfillcolor,a.markerbgcolor,q.markerfillcolor),fillAlpha:c(a.markerfillalpha,q.markerfillalpha),fillAngle:c(a.markerfillangle,q.markerfillangle),fillRatio:c(a.markerfillratio,q.markerfillratio),fillPattern:c(a.markerfillpattern,q.markerbgpattern),hoverFillColor:a.markerfillhovercolor,hoverFillAlpha:a.markerfillhoveralpha,hoverFillRatio:a.markerfillhoverratio,
hoverFillAngle:a.markerfillhoverangle,borderThickness:c(a.markerborderthickness,1),borderColor:c(a.markerbordercolor,q.markerbordercolor),borderAlpha:g(a.markerborderalpha,q.markerborderalpha),hoverBorderThickness:a.markerborderhoverthickness,hoverBorderColor:a.markerborderhovercolor,hoverBorderAlpha:a.markerborderhoveralpha,radius:g(a.markerradius&&F.trimString(a.markerradius),7),shapeId:c(a.defaultmarkershape,"circle"),labelSepChar:c(a.labelsepchar,", "),tooltipSepChar:l.tooltipSepChar,autoScale:g(a.autoscalemarkers,
0),tooltext:c(f&&f.tooltext,a.markertooltext),dataEnabled:l.useValuesForMarkers,valueToRadius:g(a.markerradiusfromvalue,1),valueMarkerAlpha:c(a.valuemarkeralpha,"75"),hideNull:g(a.hidenullmarkers,0),nullRadius:g(a.nullmarkerradius,a.markerradius,7),adjustViewPort:g(a.adjustviewportformarkers,0),startAngle:g(a.markerstartangle,90),maxRadius:g(a.maxmarkerradius,0),minRadius:g(a.minmarkerradius,0),applyAll:g(a.applyallmarkers,0),shadow:g(a.showmarkershadow,a.showshadow,0)},connectors:{showHoverEffect:g(a.showconnectorhovereffect,
1),thickness:g(a.connectorthickness,a.markerconnthickness,"2"),color:c(a.connectorcolor,a.markerconncolor,q.markerbordercolor),alpha:c(a.connectoralpha,a.markerconnalpha,"100"),hoverthickness:g(a.connectorhoverthickness,a.connectorthickness,a.markerconnthickness,"2"),hovercolor:c(a.connectorhovercolor,a.connectorcolor,a.markerconncolor,q.markerbordercolor),hoveralpha:c(a.connectorhoveralpha,a.connectoralpha,a.markerconnalpha,"100"),dashed:g(a.connectordashed,a.markerconndashed,0),dashLen:g(a.connectordashlen,
a.markerconndashlen,3),dashGap:g(a.connectordashgap,a.markerconndashgap,2),font:c(a.connectorfont,a.markerconnfont,m),fontColor:c(a.connectorfontcolor,a.markerconnfontcolor,s),fontSize:g(a.connectorfontsize,a.markerconnfontsize,parseInt(t,10)),showLabels:g(a.showconnectorlabels,a.showmarkerlabels,a.showlabels,1),labelBgColor:c(a.connectorlabelbgcolor,a.markerconnlabelbgcolor,q.plotfillcolor),labelBorderColor:c(a.connectorlabelbordercolor,a.markerconnlabelbordercolor,q.markerbordercolor),shadow:g(a.showconnectorshadow,
a.showmarkershadow,a.showshadow,0),showTooltip:g(a.showconnectortooltip,a.showmarkertooltip,l.showTooltip),tooltext:c(f&&f.connectortooltext,a.connectortooltext),hideOpen:g(a.hideopenconnectors,1)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:m,fontSize:t,lineHeight:A,color:h.plotOptions.series.dataLabels.color=s}},fillColor:K,fillAlpha:G,fillRatio:z,fillAngle:J,borderColor:B,borderAlpha:c(a.entityborderalpha,a.borderalpha,this.borderAlpha,"100"),borderThickness:g(a.showentityborder,
a.showborder,1)?g(a.entityborderthickness,a.borderthickness,1):0,scaleBorder:g(a.scaleentityborder,a.scaleborder,0),hoverFillColor:c(a.entityfillhovercolor,a.hoverfillcolor,a.hovercolor,q.plothoverfillcolor),hoverFillAlpha:c(a.entityfillhoveralpha,a.hoverfillalpha,a.hoveralpha,q.plothoverfillalpha),hoverFillRatio:c(a.entityfillhoverratio,a.hoverfillratio,a.hoverratio,q.plothoverfillratio),hoverFillAngle:c(a.entityfillhoverangle,a.hoverfillangle,a.hoverangle,q.plothoverfillangle),hoverBorderThickness:c(a.entityborderhoverthickness,
a.hoverborderthickness),hoverBorderColor:c(a.entityborderhovercolor,q.plotbordercolor),hoverBorderAlpha:c(a.entityborderhoveralpha,q.plotborderalpha),nullEntityColor:I,nullEntityAlpha:c(a.nullentityfillalpha,a.nullentityalpha,G),nullEntityRatio:c(a.nullentityfillratio,a.nullentityratio,z),nullEntityAngle:c(a.nullentityfillangle,a.nullentityangle,J),connectorColor:c(a.labelconnectorcolor,a.connectorcolor,s),connectorAlpha:c(a.labelconnectoralpha,a.connectoralpha,"100"),connectorThickness:g(a.labelconnectorthickness,
a.borderthickness,1),showHoverEffect:g(a.showentityhovereffect,a.usehovercolor,l.showHoverEffect),hoverOnNull:g(a.hoveronnull,a.entityhoveronnull,1),labelPadding:g(a.labelpadding,5),showLabels:g(a.showlabels,1),labelsOnTop:g(a.entitylabelsontop,1),includeNameInLabels:g(a.includenameinlabels,1),includeValueInLabels:g(a.includevalueinlabels,0),useSNameInTooltip:g(a.usesnameintooltip,0),useShortName:g(a.usesnameinlabels,1),labelSepChar:c(a.labelsepchar,", "),showTooltip:g(a.showentitytooltip,l.showTooltip),
tooltipSepChar:l.tooltipSepChar,tooltext:a.entitytooltext,hideNullEntities:g(a.hidenullentities,0),showHiddenEntityBorder:g(a.showhiddenentityborder,1),showNullEntityBorder:g(a.shownullentityborder,1),hiddenEntityColor:c(a.hiddenentitycolor,a.hiddenentityfillcolor,a.hiddenentityalpha||a.hiddenentityfillalpha?I:"ffffff"),hiddenEntityAlpha:c(a.hiddenentityalpha,a.hiddenentityfillalpha,.001),shadow:g(a.showshadow,this.defaultPlotShadow,q.shadow)},entitydef:{useSNameAsId:g(a.usesnameasid,0)}});h.legend.title.style.lineHeight=
da(h.legend.title.style);h.legend.itemStyle.lineHeight=da(h.legend.itemStyle);h.legend.itemHiddenStyle.lineHeight=da(h.legend.itemHiddenStyle);f=Ba(b,e,a.markermaxradius,a.markerminradius);h.markers.maxRadius=f.max;h.markers.minRadius=f.min;a.tooltipcolor&&(h.tooltip.style.color=ia(a.tooltipcolor));void 0!==c(a.clickurl)&&(k.link=a.clickurl,k.style.cursor="pointer",ma&&(k.style._cursor="hand"),h.plotOptions.series.point.events.click=function(){k.events.click.call({link:a.clickurl})});f=k.bgImageDisplayMode;
l=sa(a.bgimagevalign,"").toLowerCase();w=sa(a.bgimagehalign,"").toLowerCase();"tile"==f||"fill"==f||"fit"==f?("top"!=l&&"middle"!=l&&"bottom"!=l&&(l="middle"),"left"!=w&&"middle"!=w&&"right"!=w&&(w="middle")):("top"!=l&&"middle"!=l&&"bottom"!=l&&(l="top"),"left"!=w&&"middle"!=w&&"right"!=w&&(w="left"));k.bgImageVAlign=l;k.bgImageHAlign=w;this.parseStyles(h);da(h.title.style);da(h.subtitle.style);da(h.tooltip.style);h.plotOptions.series.allowPointSelect=!0;this.parseExportOptions(h);this.preSeriesAddition&&
this.preSeriesAddition(h,d,b,e);this.series&&this.series(d,h,this.name,b,e);this.postSeriesAddition&&this.postSeriesAddition(h,d,b,e);this.spaceManager(h,d,b,e);V.console&&V.FC_DEV_ENVIRONMENT&&V.console.log(h);return h},series:function(b,e){function d(b){for(B=b&&b.length||0;B--;)v=b[B],r=v.value,v.cleanValue=a.getCleanValue(r),v.formattedValue=null!==v.cleanValue?a.dataLabels(r):void 0,v.origValue=r,null!==v.cleanValue&&(s=P(v.cleanValue,s),u=qa(v.cleanValue,u))}function h(a,b,d){for(B=a&&a.length||
0;B--;){v=a[B];var f;a:{f=g(v.value);for(var h=void 0,k=void 0,h=void 0,m=D&&D.length||0;m--;)if(h=D[m],k=Number(h.maxvalue),h=g(h.minvalue,e.colorRange.scaleMin),f>=h&&f<=k){f=m;break a}f=null}E=f;null!==E&&(z="gradient"===t.type?e.colorRange.getColorObj(v.value).code:q&&q[E]&&c(q[E].color,q[E].code),x[E]||(x[E]=[]),z&&(v.color=v.color?v.color:z,b&&(v.alpha=v.alpha?v.alpha:b),d&&(p||v.fillhoveralpha||(v.fillhoveralpha=v.alpha),l||v.fillhovercolor||(v.fillhovercolor=v.color)),x[E].push(v)))}}var a=
this.numberFormatter,f=this.hcJSON.series,k=e.markers.valueMarkerAlpha,l=e.markers.hasHoverColor,p=e.markers.hasHoverAlpha,w=this.dataObj,m=e[pa],n=w.colorrange,q=n&&n.color,t=e.legend,x={},n={legendClick:function(){var a;if(a=this.chart)!this.legend&&(this.legend=this.plot.legend),a.legendClick(this,!this.visible)},getEventArgs:function(){var a;if(a=this.chart)return!this.legend&&(this.legend=this.plot.legend),a.getEventArgs(this)},setVisible:function(a){var b=this.data,c=this.legendItem,e=this.visible;
this.visible=a=void 0===a?!e:a;c&&t.colorizeItem&&t.colorizeItem(this,a);for(e=b&&b.length;e--;)(c=b[e].mapItem)&&(a?c.show&&c.show():c.hide&&c.hide())}},s=Infinity,u=-Infinity,v,z,C,D,r,E,A,B;d(w.data||[]);m.useValuesForMarkers&&d(w.markers&&w.markers.items||[]);m._doNotShowLegend=!0;t.type=w.colorrange&&"1"===w.colorrange.gradient?"gradient":"point";Infinity===s&&(s=void 0);-Infinity===u&&(u=void 0);m.dataMin=s;m.dataMax=u;e.colorRange=new F.colorRange({colorRange:w.colorrange,dataMin:s,dataMax:u,
defaultColor:t.minColor,numberFormatter:a});B=(D=e.colorRange.colorArr)&&D.length||0;if(0<B){for(;B--;)C=D[B],!m._doNotShowLegend||""===C.label&&void 0===C.label||(m._doNotShowLegend=!1),f.push(H({type:this.defaultSeriesType,showInLegend:!0,data:[],plot:{},name:C.label,color:C.code,rangeMin:C.minvalue,rangeMax:C.maxvalue,visible:!0},n));h(w.data||[]);m.useValuesForMarkers&&h(w.markers&&w.markers.items||[],k,!0);f=f.reverse();for(A in x)f[A]&&(f[A].data=x[A])}else f.push({type:this.defaultSeriesType,
data:[]});m._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},preliminaryScaling:function(b,c){for(var d=c.markers&&c.markers.items||[],h=d&&d.length||0,a=Infinity,f=Infinity,g=-Infinity,l=-Infinity,k,m;h--;)m=d[h],k=Number(m.x),m=Number(m.y),a=P(a,k),f=P(f,m),g=qa(g,k),l=qa(l,m);return{x:a,y:f,x1:g,y1:l}},getScalingParameters:function(b,c,d,h){var a=b/c,f=d/(b*this.baseScaleFactor),g=h/(c*this.baseScaleFactor),l=0,k=0;f>g?(f=g,l+=(d-h*a)/2,b=200/(c*f)):(k+=(h-d/a)/2,b=200/(b*f));return{scaleFactor:f,
strokeWidth:b,translateX:l,translateY:k}},calculateMarkerBounds:function(b,c,d,h,a){var f=b.markers,g=b[pa];b=g.dataMin;for(var g=g.dataMax,l=f.minRadius,k=f.maxRadius,m=f.hideNull,p=f.nullRadius,f=f.valueToRadius,n=(c=c.markers&&c.markers.items||[],c.length)||0,q=Infinity,t=Infinity,x=-Infinity,s=-Infinity,u,v,z;n--;)v=c[n],null!==v.cleanValue?(f&&void 0===v.radius&&(v.radius=l+(k-l)*(v.cleanValue-b)/(g-b)),z=Number(v.radius),u=(Number(v.x)+h)*d,v=(Number(v.y)+a)*d,q=P(q,u-z),t=P(t,v-z),x=qa(x,u+
z),s=qa(s,v+z)):m?v.__hideMarker=!0:void 0===v.radius&&(v.radius=p);return{x:q,y:t,x1:x,y1:s}},spaceManager:function(b,c,d,h){var a=b.chart,f=b[pa],g=a.spacingLeft,l=a.spacingTop,k=this.baseWidth,m=this.baseHeight;d-=a.spacingRight+g;a=h-(a.spacingBottom+l);h=f._captionBlock=this.manageTitleSpace(b,c,d,a);var p=f._legendBlock=this.placeLegendBlock(b,c,d,a-h.height,h.isBottom?h.height:0);d-=p.width;var a=a-h.height-p.height,n=p=0;f.useValuesForMarkers?(f.adjustViewPortForMarkers?(f=this.preliminaryScaling(b,
c),f.x1>k&&(k=f.x1),0>f.x&&(k+=-f.x,n=-f.x),f.y1>m&&(m=f.y1),0>f.y&&(m+=-f.y,p=-f.y),f=this.getScalingParameters(k,m,d,a),f=this.calculateMarkerBounds(b,c,f.scaleFactor*this.baseScaleFactor,n,p),b=a,c=d,0>f.x&&(g+=-f.x,d+=f.x),0>f.y&&(l+=-f.y,a+=f.y),f.x1>c&&(d-=f.x1-c),f.y1>b&&(a-=f.y1-b)):(f=this.getScalingParameters(k,m,d,a),this.calculateMarkerBounds(b,c,f.scaleFactor*this.baseScaleFactor,n,p)),f=this.getScalingParameters(k,m,d,a),g+=n*f.scaleFactor*this.baseScaleFactor,l+=p*f.scaleFactor*this.baseScaleFactor):
f=this.getScalingParameters(k,m,d,a);/bottom/i.test(h.position)||(l+=h.height);this.scaleFactor=f.scaleFactor;this.strokeWidth=f.strokeWidth;this.translateX=f.translateX+g;this.translateY=f.translateY+l},placeGLegendBlockRight:F.placeGLegendBlockRight,placeGLegendBlockBottom:F.placeGLegendBlockBottom,placeLegendBlock:function(b,c,d,h,a){var f=b.legend,g=b[pa],l=f.position.toLowerCase(),k={position:l};if("0"===c.chart.showlegend||g._doNotShowLegend)return k.height=0,k.width=0,k;"bottom"===l?(k.height=
"gradient"===f.type?this.placeGLegendBlockBottom(b,c,d,h):this.placeLegendBlockBottom(b,c,d,h),k.width=0,a&&(f.y=-a)):(d/=2,k.width="gradient"===f.type?this.placeGLegendBlockRight(b,c,d,h):this.placeLegendBlockRight(b,c,d,h),k.height=0);return k},manageTitleSpace:function(b,c,d,h){var a=this.hcJSON;b=a.title;c=a.chart;var a=a.subtitle,f=this.smartLabel,g=h/2,l=0,k=b.position.toLowerCase(),m=b.padding,p=!1,n=b.offsetX,q=b.offsetY,t=0,x={},s,u;if(""===b.text&&""===a.text)return{height:0,position:k};
isNaN(n)&&isNaN(q)||(p=!0,n=isNaN(n)?0:n,q=isNaN(q)?0:q);s=b.text;if(""!==s){f.setStyle(b.style);u=f.getOriSize(s);if(u.width>d||u.height>g)u=f.getSmartText(s,d,g),b.text=u.text,u.tooltext&&(b.originalText=u.tooltext);b.height=t=u.height;l+=t}g-=l;s=a.text;if(""!==s){f.setStyle(a.style);u=f.getOriSize(s);if(u.width>d||u.height>g)u=f.getSmartText(s,d,g),a.text=u.text,u.tooltext&&(a.originalText=u.tooltext);l+=a.height=u.height}l=l+m>g?g:l+m;k.match(/left/)?(a.align=b.align="start",a.x=b.x=c.marginLeft):
k.match(/right/)?(a.align=b.align="end",a.x=b.x=d):(a.align=b.align="middle",a.x=b.x=d/2);/bottom/.test(k)?(d=h-l+c.marginTop+m,b.y=d,a.y=d+t,p?(b.y+=q,a.y+=q,b.x+=n,a.x+=n):(c.marginBottom+=l,x.isBottom=!0)):p?(b.y+=q,a.y+=q,b.x+=n,a.x+=n):c.marginTop+=l;x.height=p?0:l;x.position=k;return x},getFirstId:function(){return this.firstEntity},getEntityPaths:function(b){var c={},d=this.entities,h;if(b){for(h in d)c[h]=d[h];return c}return d},redefineEntities:function(b,c){var d=this.entities,h={},a={},
f=0,g,l,k,m,n,p,q,t;for(q=b.length;q--;)if(g=b[q],l=g.internalid,n=g.newid?g.newid:l,k=g.sname,g=g.lname,m=d[l],l=F.trimString(l),n=F.trimString(n),m){h[n]=n={origId:l};a[l]=!0;for(p in m)n[p]=m[p];n.shortLabel=k?k:m.shortLabel;n.label=g?g:m.label}this.entities={};for(t in h)h[t].origId=t,this.entities[t.toLowerCase()]=h[t],f+=1;for(t in d)if(n=d[t],t=F.trimString(t),!a[t]){c.useSNameAsId?(this.entities[n.shortLabel.toLowerCase()]=m={},m.origId=n.shortLabel):(this.entities[t.toLowerCase()]=m={},m.origId=
t);for(p in n)m[p]=n[p];f+=1}this.entityCount=f},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",
tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerfillcolor:"backgrounddarkcolor",markerfillalpha:"backgrounddarkalpha",markerfillangle:"backgrounddarkangle",markerfillratio:"backgrounddarkratio",
plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var b=this.jsVars.hcObj,b=b.entities&&
b.entities.items,c,d=[],h,a;for(h in b)a=b[h],c=a.eJSON,d.push({id:a.id,originalId:a.originalId||a.id,label:c.label,shortlabel:c.shortLabel,value:a.value,formattedValue:a.formattedValue,toolText:a.toolText});return d},getDataAsCSV:function(){var b=this.jsVars,b=b.hcObj&&b.hcObj.entities&&b.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',d,h,a,f;for(d in b)h=b[d],a=h.eJSON,f=h.value,c+='\r\n"'+h.id+'","'+a.shortLabel+'","'+a.label+'","'+(void 0===f?"":f)+'","'+h.formattedValue+
'"';return c},getMapAttribute:function(){var b=this.jsVars.fcObj;U.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return b.getChartAttribute.apply(b,arguments)},exportMap:function(){var b=this.jsVars.fcObj;U.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return b.exportChart&&b.exportChart.apply(b,arguments)},
addMarker:function(b){this.jsVars.hcObj.markers.addMarkerItem(b)||U.raiseWarning(this,"1309264086","run","MapsRenderer~addMarker()","Failed to add marker. Check the options and try again.")},updateMarker:function(b,c){var d=this.jsVars.hcObj,h=d.markers,d=d.mapAnnotations,a;b&&(b=(b+"").toLowerCase(),h=h.items[b])&&(a=h.options,H(a,c),h=h.draw().markerShape,d.update(b,h))},removeMarker:function(b){var c=this.jsVars.hcObj.markers,d;b&&(b=(b+"").toLowerCase(),(d=c.items[b])&&d.destroy(),delete c.items[b])}}},
Y.linebase);Y("renderer.maps",{drawGraph:function(){var b=this,c=b.logic.chartInstance,d=b.paper,h=b.layers,a,f,g;b.options.nativeMessage||(h.dataset||(h.dataset=d.group("dataset").insertAfter(h.background),h.tracker=d.group("hot").insertAfter(h.dataset)),b.shadowLayer||(b.shadowLayer=h.shadow=d.group("shadow").insertBefore(h.dataset)),h.dataset&&h.dataset.hide(),h.shadow&&h.shadow.hide(),b.strokeWidth=b.logic.strokeWidth,a=b.logic.scaleFactor,b.translateX=f=b.logic.translateX,b.translateY=g=b.logic.translateY,
b.sFactor=a*b.logic.baseScaleFactor,b.transformStr=["t",f,",",g,"s",a,",",a,",0,0"].join(""),b.options.tooltip&&!1!==b.options.tooltip.enabled&&d.tooltip(b.options.tooltip.style,b.options.tooltip.shadow,b.options.tooltip.constrain),b.mapAnnotations=new F.Annotations,b.mapAnnotations.reset(null,{id:"geo",showbelow:0,autoscale:0,grpxshift:b.translateX?b.translateX:0,grpyshift:b.translateY?b.translateY:0,xscale:100*(b.sFactor?b.sFactor:1),yscale:100*(b.sFactor?b.sFactor:1),options:{useTracker:!0}}),
b.processEntityDefs(),b.drawEntities(),c.addEventListener("internal.mapdrawingcomplete",function(a){a.detachHandler();wa&&(h.dataset&&h.dataset.attr({transform:b.transformStr}),h.shadow&&h.shadow.attr({transform:b.transformStr}));h.dataset&&h.dataset.show();h.shadow&&h.shadow.show()}),b.drawMarkers())},setScaleRange:function(b,c){for(var d=this.options.series,g=d.length,a,f,k,l;g--;)if(k=d[g],f=(a=k.data)&&a.length)if(k.rangeMin>=b&&k.rangeMax<=c)k.setVisible(!0);else if(k.rangeMax<b||k.rangeMin>
c)k.setVisible(!1);else for(;f--;)k=(l=a[f].mapItem)&&l.value,isNaN(k)||""===k||(k>=b&&k<=c?l.show():l.hide())},processEntityDefs:function(){var b=this.logic,c=this.options.series,d=c&&c.length;for(b.redefineEntities(b.dataObj.entitydef||[],this.options.entitydef);d--;)c[d].chart=this},drawEntities:function(){this.entities=new m(this.logic&&this.logic.dataObj&&this.logic.dataObj.data,this,this.logic,this.layers.dataset)},drawMarkers:function(){var b=this.logic&&this.logic.dataObj&&this.logic.dataObj.markers||
null;b&&(this.markers=new x(b,this,this.group));this.options.entities.labelsOnTop||this.entities.drawLabels()},checkComplete:function(){var b=this.logic,c=b.chartInstance;this.entities&&this.entities.isReady()&&(this.mapAnnotations.draw(this),b.hasRendered=!0,U.raiseEvent("internal.mapdrawingcomplete",{renderer:this},c))}},Y["renderer.root"])},[3,2,0,"release"]]);
