/*
 FusionCharts JavaScript Library - Gantt Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.9.0
*/
FusionCharts.register("module",["private","modules.renderer.js-gantt",function(){var V=this,J=V.hcLib,Ea=V.window,ua=/msie/i.test(Ea.navigator.userAgent)&&!Ea.opera,rb=J.chartAPI,Pa=J.chartAPI,Qa=J.extend2,e=J.pluck,c=J.pluckNumber,pa=J.getFirstColor,Fa=J.graphics,ca=Fa.convertColor,fb=Fa.getDarkColor,hc=Fa.parseColor,Ca=J.parseUnsafeString,Ga=J.getFirstValue,Zb=J.getValidValue,ka=J.Raphael,ic=J.COMMASTRING,La=J.setLineHeight,Eb=J.getDashStyle,Fb=J.toRaphaelColor,Ra=J.each,jc=J.FC_CONFIG_STRING,Ma=
"rgba(192,192,192,"+(ua?.002:1E-6)+")",$b=Fa.mapSymbolName,ua=Math,Ha=ua.ceil,va=ua.round,fa=ua.max,Da=ua.min,ac=ua.abs,Sa=parseInt,Gb=parseFloat,kc={pageX:0,pageY:0},Y=J.plotEventHandler,na,W,sb=J.hasTouch=void 0!==Ea.document.documentElement.ontouchstart,lc=J.addEvent,mc=J.removeEvent,Ta=function(b){return void 0!==b&&null!==b},Ua={left:"start",right:"end",center:"middle"},gb={left:0,right:1,center:.5,undefined:.5},tb={top:1,bottom:0,middle:.5,undefined:.5},Va={left:5,right:-5,center:0,undefined:0},
Ea=!/fusioncharts\.com$/i.test(Ea.location.hostname),Na=function(b,a){this.min=b.min;this.max=c(b.visibleMax,b.max);this.pixelValueRatio=a/(this.max-this.min);this.startPixel=b.chart.marginLeft+b.chart.ganttStartX};Na.prototype={getPixel:function(b){return this.startPixel+(b-this.min)*this.pixelValueRatio}};Na.prototype.constructor=Na;rb("gantt",{friendlyName:"Gantt Chart",rendererId:"gantt",standaloneInit:!0,defaultSeriesType:"gantt",canvasborderthickness:1,defaultPlotShadow:1,creditLabel:Ea,fireGroupEvent:!0,
defaultPaletteOptions:function(){var b=arguments;return J.extend2(J.extend2(J.extend2(J.extend2({},b[0]),b[1]),b[2]),b[3])}(Qa({},J.defaultGaugePaletteOptions),{paletteColors:["AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),
"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" ")],
bgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],bgAngle:[270,270,270,270,270],bgRatio:["100","100","100","100","100"],bgAlpha:["100","100","100","100","100"],canvasBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],canvasBgAngle:[0,0,0,0,0],canvasBgAlpha:["100","100","100","100","100"],canvasBgRatio:["","","","",""],canvasBorderColor:["545454","545454","415D6F","845001","68001B"],canvasBorderAlpha:[100,100,100,90,100],gridColor:["DDDDDD","D8DCC5","99C4CD","DEC49C","FEC1D0"],gridResizeBarColor:["999999",
"545454","415D6F","845001","D55979"],categoryBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],dataTableBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],toolTipBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],toolTipBorderColor:["545454","545454","415D6F","845001","68001B"],baseFontColor:["555555","60634E","025B6A","A15E01","68001B"],borderColor:["767575","545454","415D6F","845001","68001B"],borderAlpha:[50,50,50,50,50],legendBgColor:["ffffff","ffffff","ffffff","ffffff","ffffff"],
legendBorderColor:["666666","545454","415D6F","845001","D55979"],plotBorderColor:["999999","8A8A8A","6BA9B6","C1934D","FC819F"],plotFillColor:["EEEEEE","D8DCC5","BCD8DE","E9D8BE","FEDAE3"],scrollBarColor:["EEEEEE","D8DCC5","99C4CD","DEC49C","FEC1D0"]}),charttopmargin:10,chartbottommargin:20,series:function(){var b=this.dataObj,a=b.chart,H=(H=b.categories)||[],d=H.length,q=this.hcJSON,k=q.chart,m=q[jc],y=this.smartLabel,f=this.colorManager,g=q.categories={},v=[],p=this.inCanvasStyle,s=this.numberFormatter,
C=Infinity,l=-Infinity,t=k.origW-k.marginLeft-k.marginRight,D=k.origH-k.marginTop-k.marginBottom,n=b.processes||{},h=n&&n.process,x=h&&h.length,w=Sa(p.fontSize,10),O=b.datatable,T=O&&O.datacolumn,F=T&&T.length,ea=b.connectors,L=ea&&ea.length,M=q.connectors=[],N=b.milestones&&b.milestones.milestone,B=N&&N.length,Z=q.milestone=[],G=b.tasks,$=G&&G.task,K=$&&$.length,u=0,r=0,bc=c(a.forceganttwidthpercent,0),aa=0,Y=0,W=!1,ka={top:"top",bottom:"bottom"},A={top:"top",bottom:"bottom",undefined:"middle"},
R={right:"right",left:"left"},ba={right:"right",left:"left",undefined:"center"},E=q.dataTable={},hb=Infinity,ib=-Infinity,na=q.processIDMap=[],V,ua,Ea=c(a.dateintooltip,1),Ha=b.legend&&b.legend.item,Fa=q.tasksMap||(q.tasksMap={}),Na=0,Pa=0,ub,za,Hb,Ib,jb,vb,Ra,Jb,Kb,qa,wa,Aa,Ua,gb,Va,Qb,wb,rb,xa,oa,kb,Q,Lb,Wa,Xa,Mb,Nb,Ba,la,ma,Ya,Za,$a,lb,ab,bb,Ia,Ja,ga,sb,Rb,ha,ia,da,mb,nb,cb,U,I,Sb,db,xb,Ka,yb,Tb,Ob,ob,Ub,zb,Ab,Bb,Cb,Db,Pb,pb,tb,cc,dc,ec,Oa,S,fc,sa,P,ya,ra,qb,ja,Vb,Wb,Xb,Yb,ta,eb,gc,z,X;if(x){q.tasks=
[];delete q.yAxis;delete q.xAxis;k.backgroundColor=ca(e(a.bgcolor,"FFFFFF"),e(a.bgalpha,f.getColor("bgAlpha")));c(a.showborder,0)||(k.borderWidth=0);k.plotBorderColor=ca(e(a.canvasbordercolor,f.getColor("canvasBorderColor")),0===c(a.showcanvasborder,1)?0:e(a.canvasborderalpha,100));k.backgroundColor={FCcolor:{color:e(a.bgcolor,"FFFFFF"),alpha:e(a.bgalpha,f.getColor("bgAlpha")),angle:e(a.bgangle,f.getColor("bgAngle")),ratio:e(a.bgratio,f.getColor("bgRatio"))}};k.plotBackgroundColor={FCcolor:{color:e(a.canvasbgcolor,
f.getColor("canvasBgColor")),alpha:e(a.canvasbgalpha,f.getColor("canvasBgAlpha")),angle:e(a.canvasbgangle,f.getColor("canvasBgAngle")),ratio:e(a.canvasbgratio,f.getColor("canvasBgRatio"))}};k.plotBorderWidth=c(a.canvasborderthickness,1);k.outputDateFormat=e(a.outputdateformat,k.dateFormat);k.extendCategoryBg=c(a.extendcategorybg,0);k.ganttLineColor=ca(e(a.ganttlinecolor,f.getColor("gridColor")),c(a.ganttlinealpha,100));k.ganttLineThickness=c(a.ganttlinethickness,1);k.ganttLineDashStyle=c(a.ganttlinedashed,
0)?Eb(c(a.ganttlinedashlen,1),a.ganttlinedashgap,k.ganttLineThickness):"none";k.gridBorderColor=ca(e(a.gridbordercolor,f.getColor("gridColor")),c(a.gridborderalpha,100));k.gridBorderThickness=c(a.gridborderthickness,1);k.gridBorderDashStyle=c(a.gridborderdashed,0)?Eb(c(a.gridborderdashlen,1),a.gridborderdashgap,k.gridborderThickness):"none";k.showSlackAsFill=c(a.showslackasfill,1);k.slackFillColor=pa(e(a.slackfillcolor,"FF5E5E"));k.gridResizeBarColor=ca(e(a.gridresizebarcolor,f.getColor("gridResizeBarColor")),
c(a.gridresizebaralpha,100));k.gridResizeBarThickness=c(a.gridresizebarthickness,1);k.taskBarRoundRadius=c(a.taskbarroundradius,0);k.taskBarFillMix=a.taskbarfillmix;k.taskBarFillRatio=a.taskbarfillratio;void 0===k.taskBarFillMix&&(k.taskBarFillMix="{light-10},{dark-20},{light-50},{light-85}");void 0===k.taskBarFillRatio&&(k.taskBarFillRatio="0,8,84,8");k.connectorExtension=c(a.connectorextension,10);k.clickURL=e(a.clickurl,"");k.annRenderDelay=a.annrenderdelay;k.taskDatePadding=c(a.taskdatepadding,
3);k.taskLabelPadding=c(a.tasklabelspadding,2);k.ganttStartX=c(a.ganttwidthpercent,65);100<k.ganttStartX&&(k.ganttStartX=100);Aa=k.ganttStartX=.01*(100-k.ganttStartX)*t;k.gridWidth=t-k.ganttStartX;gc=c(a.showfulldatatable,1);cb=n.width;cb=c(k.ganttStartX*(/\%/g.test(cb)&&.01*Gb(cb,10))||cb);Aa-=c(cb,0);V=va(cb);Y+=1;for(z=0;z<F;z+=1)Jb=T[z].width,Kb=c(k.ganttStartX*(/\%/g.test(Jb)&&.01*Gb(Jb,10))||Jb),Aa-=c(Kb,0),Kb=T[z].width=va(Kb),Y+=1;0<=Aa?Aa/=Y:(W=!0,Aa=k.ganttStartX/Y);if(bc||!gc)for((isNaN(V)||
W)&&(V=Aa),z=0;z<F;z+=1)(isNaN(T[z].width)||W)&&(T[z].width=Aa);for(z=0;z<d;z+=1){ia=H[z];C=Infinity;l=-Infinity;mb=e(ia.bgcolor,f.getColor("categoryBgColor"));nb=c(ia.bgalpha,100);Ya=e(ia.font,p.fontFamily);Za=c(ia.fontsize,w+1);$a=e(ia.fontcolor,p.color);lb=c(ia.isbold,1);ab=c(ia.isitalic,0);bb=c(ia.isunderline,0);c(ia.verticalpadding,3);Ia=e(ia.align,"center").toLowerCase();Ja=e(ia.valign,"middle").toLowerCase();sb=(Rb=ia.category)&&Rb.length;Oa=0;ja={};for(X=0;X<sb;X+=1)ha=Rb[X],la=s.getDateValue(ha.start).ms,
ma=s.getDateValue(ha.end).ms,isNaN(la)&&(la=void 0),la>l&&(l=la),la<=C&&(C=la),isNaN(ma)&&(ma=void 0),ma>l&&(l=ma),ma<=C&&(C=ma),ga=Ca(e(ha.label,ha.name)),S={color:pa(e(ha.fontcolor,$a)),fontFamily:e(ha.font,Ya),fontSize:c(ha.fontsize,Za)+"px",fontWeight:c(ha.isbold,lb)&&"bold"||"normal",fontStyle:c(ha.isitalic,ab)&&"italic"||"normal",textDecoration:c(ha.isunderline,bb)&&"underline"||"none"},La(S),y.setStyle(S),qa=y.getOriSize(ga),Oa=fa(Oa,qa.height),P="FCCAT_"+z+"_"+X,Hb=e(ha.hoverbandcolor,ia.hoverbandcolor,
a.categoryhoverbandcolor,a.hoverbandcolor,f.getColor("gridColor")),Ib=c(ha.hoverbandalpha,ia.hoverbandalpha,a.categoryhoverbandalpha,a.hoverbandalpha,30),jb=c(ha.showhoverband,ia.showhoverband,a.showcategoryhoverband,a.showhoverband,a.showhovereffect,1),g[P]={text:ga,style:S,start:la,end:ma,index:X,isLast:z===d-1,bgColor:ca(e(ha.bgcolor,mb),c(ha.bgalpha,nb)),dimension:ja,link:ha.link,align:ba[[e(ha.align,Ia).toLowerCase()]],vAlign:A[ka[e(ha.valign,Ja).toLowerCase()]],hoverColor:ca(Hb,Ib),useHover:jb,
usePlotHover:c(ha.showganttpanehoverband,ia.showganttpanehoverband,a.showganttpaneverticalhoverband,jb)},g[ya]&&(g[ya].nextCol=g[P],g[P].prevCol=g[ya]),ya=P;if(xb=g["FCCAT_"+z+"_0"])g[P].first=xb,xb.last=g[P],g[db]&&(g[db].nextRow=xb,xb.prevRow=g[db]);db=P;ja.h=Oa+5+2*c(ia.verticalpadding,3);ja.y=r;ja.min=C;ja.max=l;ja.numCat=X;r+=ja.h;ib=fa(ib,l);hb=Da(hb,C)}g.min=hb;g.max=ib;if(x){Oa=wa=0;eb="right"===e(n.positioningrid,"left").toLowerCase();S={color:pa(e(n.headerfontcolor,p.color)),fontFamily:e(n.headerfont,
p.fontFamily),fontSize:c(n.headerfontsize,w+3)+"px",fontWeight:c(n.headerisbold,1)&&"bold"||"normal",fontStyle:c(n.headerisitalic,0)&&"italic"||"normal",textDecoration:c(n.headerisunderline,0)&&"underline"||"none"};La(S);ga=Ca(n.headertext);y.setStyle(S);qa=y.getOriSize(ga);wa=fa(wa,qa.width);Ia=ba[R[e(n.headeralign,"center").toLowerCase()]];Ja=A[ka[e(n.headervalign,"middle").toLowerCase()]];ja={};P=ra=db="processHeader";E.processHeader={text:ga,style:S,align:Ia,vAlign:Ja,isHeader:!0,link:e(n.headerlink),
dimension:{x:0,w:0,h:fa(qa.height,r)},bgColor:ca(e(n.headerbgcolor,f.getColor("dataTableBgColor")),c(n.headerbgalpha,100)),key:P,isLast:eb,drawResizer:!eb&&F,prevCol:null,nextCol:null,prevRow:null,nextRow:null};mb=e(n.bgcolor,f.getColor("dataTableBgColor"));nb=c(n.bgalpha,100);Ya=e(n.font,p.fontFamily);Za=c(n.fontsize,w);$a=e(n.fontcolor,p.color);lb=c(n.isbold,0);ab=c(n.isitalic,0);bb=c(n.isunderline,0);Ia=e(n.align,"center").toLowerCase();Ja=e(n.valign,"middle").toLowerCase();for(z=0;z<x;z+=1)da=
h[z],Hb=e(da.hoverbandcolor,n.hoverbandcolor,a.processhoverbandcolor,a.hoverbandcolor,f.getColor("gridColor")),Ib=c(da.hoverbandalpha,n.hoverbandalpha,a.processhoverbandalpha,a.hoverbandalpha,30),jb=c(da.showhoverband,n.showhoverband,a.showprocesshoverband,a.showhoverband,a.showhovereffect,1),S={color:pa(e(da.fontcolor,$a)),fontSize:c(da.fontsize,Za)+"px",fontFamily:e(da.font,Ya),fontWeight:c(da.isbold,lb)&&"bold"||"normal",fontStyle:c(da.isitalic,ab)&&"italic"||"normal",textDecoration:c(da.isunderline,
bb)&&"underline"||"none"},La(S),ga=Ca(e(da.label,da.name)),y.setStyle(S),qa=y.getOriSize(ga),Oa=fa(Oa,qa.height),wa=fa(wa,qa.width),ya=P,P=e(da.id,"__FCDPID__"+z).toUpperCase(),E[P]&&(P="__FCDPID__"+z),na[z]=P,Ta(ub=c(da.height,a.rowheight))&&(ub=ac(ub),Na+=ub||0,Pa+=1),E[P]={text:qa.text,style:S,link:da.link,id:P,processHeight:ub,labelHeight:qa.height,align:ba[[e(da.align,Ia).toLowerCase()]],vAlign:A[ka[e(da.valign,Ja).toLowerCase()]],bgColor:ca(e(da.bgcolor,mb),c(da.bgalpha,nb)),prevCol:E[ya],dimension:{},
hoverColor:ca(Hb,Ib),useHover:jb,usePlotHover:c(da.showganttpanehoverband,n.showganttpanehoverband,a.showganttpanehorizontalhoverband,jb),isLast:eb,nextCol:null,prevRow:null,nextRow:null},E[ya]&&(E[ya].nextCol=E[P]);E[P].first=E[ra];E[ra].last=E[P];E[ra].processCount=x;E[ra].countDefinedHeight=Pa;E[ra].totalHeight=Na;ua=E[ra].maxProcessHeight=Oa+8;isNaN(V)&&(V=wa+10);aa+=V;ja.x=0;E[ra].dimension.w=ja.w=V;ja.h=ua=fa((D-E[ra].dimension.h)/x,ua)}eb&&(aa=0);if(F)for(q.datacolumns=[],z=0;z<F;z+=1){U=T[z];
wa=0;mb=pa(e(U.bgcolor,O.bgcolor,f.getColor("dataTableBgColor")));nb=c(U.bgalpha,O.bgalpha,100);Ya=e(U.font,O.font,p.fontFamily);$a=pa(e(U.fontcolor,O.fontcolor,p.color));Za=c(U.fontsize,O.fontsize,w);lb=c(U.isbold,O.isbold,0);ab=c(U.isitalic,O.isitalic,0);bb=c(U.isunderline,O.isunderline,0);Ia=ba[R[e(U.align,O.align,"center").toLowerCase()]];Ja=A[ka[e(U.valign,O.valign,"middle").toLowerCase()]];S={color:pa(e(U.headerfontcolor,O.headerfontcolor,$a)),fontFamily:e(U.headerfont,O.headerfont,Ya),fontSize:c(U.headerfontsize,
O.headerfontsize,Za+3)+"px",fontWeight:c(U.headerisbold,O.headerisbold,1)&&"bold"||"normal",fontStyle:c(U.headerisitalic,O.headerisitalic,ab)&&"italic"||"normal",textDecoration:c(U.headerisunderline,O.headerisunderline,bb)&&"underline"||"none"};La(S);ga=Ca(U.headertext);y.setStyle(S);qa=y.getOriSize(ga);wa=fa(wa,qa.width);P=ra="_FCDtHeader_"+z;kb=E[P]={text:ga,style:S,align:ba[R[e(U.headeralign,O.headeralign,Ia).toLowerCase()]],vAlign:A[ka[e(U.headervalign,O.headervalign,Ja).toLowerCase()]],link:e(U.headerlink),
drawResizer:eb||z<F-1,dimension:{x:0+aa,w:U.width,h:E.processHeader&&E.processHeader.dimension.h},isHeader:!0,key:P,bgColor:ca(e(U.headerbgcolor,O.headerbgcolor,f.getColor("dataTableBgColor")),c(U.headerbgalpha,O.headerbgalpha,100))};kb.data=[];fc=U.text||[];qb=E.processHeader;Ka=E[db];Ka.nextRow=E[P];E[P].prevRow=Ka;qb=qb.nextCol;Ka=Ka.nextCol;ja={};db=ra;for(X=0;qb;qb=qb.nextCol,Ka=Ka.nextCol,X+=1)ya=P,P="_FCDt_"+z+"_"+X,(sa=fc[X])?(S={fontFamily:e(sa.font,Ya),color:pa(e(sa.fontcolor,$a)),fontSize:c(sa.fontsize,
Za)+"px",fontWeight:c(sa.isbold,lb)&&"bold"||"normal",fontStyle:c(sa.isitalic,ab)&&"italic"||"normal",textDecoration:c(sa.isunderline,bb)&&"underline"||"none"},La(S),y.setStyle(S),ga=Ca(sa.label),qa=y.getOriSize(ga),wa=fa(wa,qa.width),E[P]={text:ga,style:S,link:e(sa.link,""),bgColor:ca(e(sa.bgcolor,mb),c(sa.bgalpha,nb)),align:ba[R[e(sa.align,Ia).toLowerCase()]],vAlign:A[ka[e(sa.valign,Ja).toLowerCase()]],prevCol:E[ya],dimension:ja,nextCol:null,nextRow:null,prevRow:null}):E[P]={prevCol:E[ya],dimension:ja,
isNaN:!0,nextCol:null,nextRow:null,prevRow:null},E[ya].nextCol=E[P],E[P].prevRow=Ka,Ka.nextRow=E[P],E[P].hoverColor=E[na[X]].hoverColor,E[P].useHover=E[na[X]].useHover,E[P].usePlotHover=E[na[X]].usePlotHover;E[P].first=E[ra];E[ra].last=E[P];isNaN(U.width)?kb.width=wa+10:kb.width=U.width;ja.x=0+aa;aa+=E[ra].dimension.w=ja.w=kb.width;ja.h=ua;q.datacolumns.push(kb)}eb&&(da=E.processHeader,da.dimension.x=da.nextCol.dimension.x=aa,aa+=V);bc||(k.ganttStartX=Da(k.ganttStartX,aa));k.totalGridWidth=aa;Wb=
b.trendlines||{};q.trendlines=[];for(z=0;z<Wb.length;z+=1)for(B=(Xb=Wb[z].line)&&Xb.length,X=0;X<B;X+=1)ta=Xb[X],Yb=c(ta.istrendzone,0),Ba=e(ta.color,f.getColor("legendBorderColor")),S=Qa({},m.trendStyle),S.color=ca(Ba),La(S),q.trendlines.push({start:s.getDateValue(ta.start).ms,end:s.getDateValue(ta.end).ms,displayValue:Ca(e(ta.displayvalue,ta.start)),color:ca(Ba,c(ta.alpha,Yb?40:99)),style:S,isTrendZone:Yb,dashedStyle:c(ta.dashed,0)?Eb(c(ta.dashlen,3),c(ta.dashgap,3),c(ta.thickness,1)):"none",thickness:c(ta.thickness,
1)});if(K){C=Infinity;l=-Infinity;c(a.taskbarroundradius,0);Xa=a.taskbarfillmix;Mb=a.taskbarfillratio;void 0===Xa&&(Xa="{light-10},{dark-20},{light-50},{light-85}");void 0===Mb&&(Mb="0,8,84,8");k.shadow=c(a.showshadow,1);Ra=c(a.showslackasfill,1);for(z=0;z<K;z+=1)I=$[z],Sb=u%x,la=s.getDateValue(I.start).ms,ma=s.getDateValue(I.end).ms,P=e(E[Ga(I.processid,"").toUpperCase()],E["__FCDPID__"+Sb],E[na[Sb]]).id.toUpperCase(),yb=c(I.alpha,G.alpha,100),Ba=e(I.color,G.color,f.getColor("plotFillColor")),Ob=
c(I.borderalpha,G.borderalpha,100),Tb=e(I.bordercolor,G.bordercolor,f.getColor("plotBorderColor")),isNaN(la)&&(la=void 0),la>l&&(l=la),la<=C&&(C=la),isNaN(ma)&&(ma=void 0),ma>l&&(l=ma),ma<=C&&(C=ma),S={color:pa(e(I.fontcolor,G.fontcolor,p.color)),fontSize:c(I.fontsize,G.fontsize,w)+"px",fontFamily:e(I.font,G.font,p.fontFamily)},La(S),u+=1,ob=f.parseColorMix(Ba,Xa),Ub=f.parseAlphaList(yb.toString(),ob.length),zb=f.parseRatioList(Mb,ob.length),Ab=c(I.angle,G.angle,270),Pb=f.parseColorMix(e(I.slackfillcolor,
G.slackfillcolor,a.slackfillcolor,"FF5E5E"),Xa),pb=Da(c(I.percentcomplete,-1),100),ga=Ga(e(I.label,I.name),""),Db="",c(I.showlabel,I.showname,G.showlabels,G.showname,a.showtasklabels,a.showtasknames,0)&&(Db=ga),c(I.showpercentlabel,G.showpercentlabel,a.showpercentlabel,0)&&-1!==pb&&(Db+=" "+pb+"%"),tb={FCcolor:{color:ob.join(),alpha:Ub,ratio:zb,angle:Ab}},Pb=Ra?{FCcolor:{color:Pb.join(),alpha:Ub,ratio:zb,angle:Ab}}:Ma,cc={FCcolor:{color:f.parseColorMix(e(I.hoverfillcolor,G.hoverfillcolor,a.taskhoverfillcolor,
fb(Ba,80)),Xa).join(),alpha:f.parseAlphaList(e(I.hoverfillalpha,G.hoverfillalpha,a.taskhoverfillalpha,yb).toString(),ob.length),ratio:zb,angle:Ab}},dc=ca(e(I.hoverbordercolor,G.hoverbordercolor,a.taskhoverbordercolor,fb(Tb,80)),e(I.hoverborderalpha,G.hoverborderalpha,a.taskhoverborderalpha,Ob)),ec=Ra?{FCcolor:{color:f.parseColorMix(fb(e(I.slackhoverfillcolor,G.slackhoverfillcolor,a.slackhoverfillcolor,a.slackfillcolor,"FF5E5E"),80),Xa).join(),alpha:f.parseAlphaList(e(I.slackhoverfillalpha,G.slackhoverfillalpha,
a.slackhoverfillalpha,yb).toString(),ob.length),ratio:zb,angle:Ab}}:Ma,Bb=s.getFormattedDate(la),Cb=s.getFormattedDate(ma),za=Zb(Ca(e(I.tooltext,I.hovertext,G.plottooltext,m.tooltext))),za=void 0!==za?J.parseTooltext(za,[3,28,29,30,31],{end:Cb,start:Bb,label:ga,percentComplete:-1!==pb?s.percentValue(pb):"",processName:E[P]&&E[P].text},I):(""!==ga?ga+(Ea?", ":""):"")+(Ea?Bb+" - "+Cb:""),Wa=Ga(I.id,"").toUpperCase(),Fa[Ga(Wa,z)]={dataObj:{processId:P,label:Db,labelAlign:ba[[e(I.labelalign,a.tasklabelsalign,
"center").toLowerCase()]],link:I.link,start:la,end:ma,id:Ga(I.id,"").toUpperCase(),showAsGroup:c(I.showasgroup,0),animation:c(I.animation,a.animation,a.defaultanimation,1),style:S,percentComplete:pb,color:Fb(tb),slackColor:Fb(Pb),hoverFillColor:Fb(cc),hoverBorderColor:dc,slackHoverColor:Fb(ec),showHoverEffect:c(I.showhovereffect,G.showhovereffect,a.showtaskhovereffect,a.showhovereffect,1),shadow:{opacity:fa(yb,Ob)/100,inverted:!0},borderColor:ca(Tb,Ob),borderThickness:c(I.showborder,G.showborder,
1)?c(I.borderthickness,G.borderthickness,1):0,height:e(I.height,"35%"),topPadding:e(I.toppadding,"35%"),showPercentLabel:c(I.showpercentlabel,G.showpercentlabel,a.showpercentlabel,0),startDate:c(I.showstartdate,G.showstartdate,a.showtaskstartdate)?Bb:void 0,endDate:c(I.showenddate,G.showenddate,a.showtaskenddate)?Cb:void 0,toolText:za,_start:I.start,_end:I.end,_formatSDate:Bb,_formatEDate:Cb,_label:ga}},v.push(Fa[Ga(Wa,z)].dataObj);ib=fa(ib,l);hb=Da(hb,C)}q.series.push({showInLegend:!1,data:v});B=
N&&N.length;for(z=0;z<B;z+=1)Q=N[z],Wa=Ga(Q.taskid,"").toUpperCase(),Nb=e(Q.shape,"polygon").toLowerCase(),Lb=c(Q.numsides,5),Vb=0,"star"===Nb?Vb=.4:(Nb=$b(Lb),Nb=$b(Lb).split("-")[0]),Ba=e(Q.color,f.getColor("legendBorderColor")),za=Zb(Ca(e(Q.tooltext,Q.hovertext,a.milestonetooltext))),void 0!==za&&Fa[Wa]?(I=Fa[Wa].dataObj,za=J.parseTooltext(za,[28,32,33,34,35,36],{date:s.getFormattedDate(Q.date),taskStartDate:I._formatSDate,taskEndDate:I._formatEDate,taskLabel:I._label,taskPercentComplete:-1!==
I.percentComplete?s.percentValue(I.percentComplete):"",processName:E[I.processId]&&E[I.processId].text},Q)):za=s.getFormattedDate(Q.date),S={color:pa(e(Q.fontcolor,a.milestonefontcolor,p.color)),fontSize:c(Q.fontsize,a.milestonefontsize,w)+"px",fontFamily:e(Q.font,a.milestonefont,p.fontFamily),fontWeight:c(Q.fontbold,a.milestonefontbold,0)&&"bold"||"normal",fontStyle:c(Q.fontitalic,a.milestonefontitalic,0)&&"italic"||"normal"},La(S),Z.push({numSides:Lb,startAngle:c(Q.startangle,90),radius:Q.radius,
origDate:Q.date,date:s.getDateValue(Q.date),fillColor:pa(Ba),fillAlpha:.01*c(Q.fillalpha,Q.alpha,100),borderColor:pa(e(Q.bordercolor,Ba)),borderAlpha:.01*c(Q.borderalpha,Q.alpha,100),displayValue:Ca(Q.label),style:S,hoverFillColor:pa(e(Q.hoverfillcolor,a.milestonehoverfillcolor,fb(Ba,80))),hoverFillAlpha:.01*c(Q.hoverfillalpha,a.milestonehoverfillalpha,Q.fillalpha,Q.alpha,100),hoverBorderColor:pa(e(Q.hoverbordercolor,a.milestonehoverbordercolor,fb(e(Q.bordercolor,Ba),80))),hoverBorderAlpha:.01*c(Q.hoverborderalpha,
a.milestonehoverborderalpha,Q.borderalpha,Q.alpha,100),showHoverEffect:c(Q.showhovereffect,a.showmilestonehovereffect,a.showhovereffect,1),depth:Vb,taskId:Wa,borderThickness:c(Q.borderthickness,1),link:Q.link,toolText:za});for(z=0;z<L;z+=1)if(gb=(Ua=(xa=ea[z])&&xa.connector)&&Ua.length)for(X=0;X<gb;X+=1)oa=Ua[X],Va=e(oa.color,xa.color,f.getColor("plotBorderColor")),Qb=c(oa.alpha,xa.alpha,100),wb=c(oa.thickness,xa.thickness,1),rb=c(oa.isdashed,xa.isdashed,1),M.push({fromTaskId:Ga(oa.fromtaskid,"").toUpperCase(),
toTaskId:Ga(oa.totaskid,"").toUpperCase(),fromTaskConnectStart:c(oa.fromtaskconnectstart,0),toTaskConnectStart:c(oa.totaskconnectstart,1),color:ca(Va),alpha:.01*Qb,link:oa.link,showHoverEffect:c(oa.showhovereffect,xa.showhovereffect,a.showconnectorhovereffect,a.showhovereffect,1),hoverColor:ca(e(oa.hovercolor,xa.hovercolor,a.connectorhovercolor,fb(Va,80)),c(oa.hoveralpha,xa.hoveralpha,a.connectorhoveralpha,Qb)),hoverThickness:c(oa.hoverthickness,xa.hoverthickness,a.connectorhoverthickness,wb),thickness:wb,
dashedStyle:rb?Eb(c(oa.dashlen,xa.dashlen,5),c(oa.dashgap,xa.dashgap,wb),wb):"none"});q.legend.enabled=Boolean(c(a.showlegend,1));q.legend.interactiveLegend=!1;q.legend.itemStyle.cursor="default";q.legend.itemHoverStyle={cursor:"inherit"};B=Ha&&Ha.length;for(z=0;z<B;z+=1)vb=Ha[z],Ta(vb.label)&&""!==vb.label&&q.series.push({name:Ca(vb.label),showInLegend:!0,type:!1,color:hc(e(vb.color,f.getPlotColor()))});q.max=ib;q.min=hb;q.chart.hasScroll=!0;return q}},spaceManager:function(b,a,H,d){this.titleSpaceManager(b,
a,H,.3*d);var q=this.numberFormatter,k=b.chart,m=a.chart,y=b.dataTable,f=b.categories,g=b.scrollOptions={},v=y.__scrollOptions={},p=y.processHeader;d=d-k.marginTop-k.marginBottom;H=H-k.marginLeft-k.marginRight;var s=k.totalGridWidth,C=b.verticalScroll={enabled:c(m.useverticalscrolling,1)},l=c(m.ganttpaneduration,-1),t=e(m.ganttpanedurationunit,"s").toLowerCase(),D=q.getDateValue(m.scrolltodate).ms,n=p&&p.maxProcessHeight,h,x,q=0;if(p){h=p.processCount-p.countDefinedHeight;b.legend.enabled&&(d-=this.placeLegendBlockBottom(b,
a,H,d/2));d-=p.dimension.h;g.padding=c(m.scrollpadding,b.chart.plotBorderWidth/2);g.height=c(m.scrollheight,16);g.showButtons=!!c(m.scrollshowbuttons,1);g.buttonPadding=c(m.scrollbtnpadding,0);g.flatScrollBars=c(m.flatscrollbars,0);g.color=pa(e(m.scrollcolor,this.colorManager.getColor("altHGridColor")));a=g.height+g.padding;s>k.ganttStartX&&(v.enabled=!0,v.startPercent=Boolean(c(m.scrolltoend,0)));H-=k.ganttStartX;f.scroll={};g=new Date(f&&f.min);if(-1!==l){switch(t){case "y":g.setYear(g.getFullYear()+
l);break;case "m":g.setMonth(g.getMonth()+l);break;case "d":g.setDate(g.getDate()+l);break;case "h":g.setHours(g.getHours()+l);break;case "mn":g.setMinutes(g.getMinutes()+l);break;default:g.setSeconds(g.getSeconds()+l)}g=g.getTime();g>b.min&&g<b.max&&(b.visibleMax=g,f.scroll.enabled=!0)}if(v.enabled||f.scroll.enabled)d-=a;v=d-p.totalHeight;g=v/(h?h:p.processCount);!c(m.forcerowheight,0)&&!h&&p.totalHeight<d&&(g=d/p.processCount,v=d,x=!0);n>g&&(n=3>n-g?g:v/va(v/n));p.maxProcessHeight=n;C.enabled&&
g<n&&h||0>g?(v=n,C.startPercent=Boolean(c(m.scrolltoend,0)),H-=a):(C.enabled=!1,v=g);f.scroll.startPercent=c(m.scrolltoend,0);if(Infinity===b.min||-Infinity===b.max||b.min===b.max)b.min=f.min=0,b.max=f.max=1;if(Infinity===f.min||-Infinity===f.max)f.min=b.min,f.max=b.max;f.axis=new Na(b,H);f.startX=f.axis.getPixel(Da(f.min,b.min));f.endX=f.axis.getPixel(fa(f.max,b.max));f.visibleW=H;D&&D>f.min&&D<f.max&&(f.scroll.startPercent=Da((f.axis.getPixel(D)-f.startX)/(f.endX-f.startX-f.visibleW),1));for(p=
p.nextCol;p;){q+=p.dimension.h=x?v:p.processHeight||v;if(b=p.nextRow)for(;b;)b.dimension=Qa({},b.dimension),b.dimension.h=p.dimension.h,b=b.nextRow;p=p.nextCol}y.processHeader.totalPH=y.processHeader.dimension.h+q;k.processHeight=d+y.processHeader.dimension.h}}},rb.gaugebase);Pa("renderer.gantt",{drawProcess:function(b){var a=this,c=a.options,d=c.chart,q=a.paper,k=a.logic,m=k.smartLabel,y=a.canvasTop,f=a.canvasLeft,g=a.layers,v=g.gridLayer,p=g.gridHeaderLayer,s=d.gridBorderThickness,C=.5*s,l=d.gridBorderColor,
t=d.gridBorderDashStyle,D=0,n=0,h=[],x=y,w=b.dimension.w||16,O=b.dimension.x||0,T=c.dataTable.processHeader,F=T.nextCol.dimension.h,ea=T.totalPH,k=ca(e(k.dataObj.chart.rolloverbandcolor,"#FF0000"),e(k.dataObj.chart.rolloverbandalpha,30)),L=T.items||(T.items={}),c=c.categories||{},M,N,B,Z,G,$,K,u,r,J,aa;L.hoverEle||(L.hoverEle=q.rect(c.startX,0,c.endX,F,0,g.dataset).attr({fill:k,visibility:"hidden","stroke-width":0}));r=function(b){Y.call(this,a,b,"ProcessClick")};J=function(b){na=clearTimeout(na);
if(!W||W.removed)W=null;W&&a.gridOutHandler.call(W);a.gridHoverHandler.call(this);Y.call(this,a,b,"ProcessRollOver")};for(aa=function(b){W=this;na=clearTimeout(na);na=setTimeout(function(){a.gridOutHandler.call(W)},500);Y.call(W,a,b,"ProcessRollOut")};b;)u=b.dimension,K=f+O,B=b.text,B=b.align,L=b.items||(b.items={}),F=b.link,N=b.isHeader?p:v,Z=L.background,c=Ha(x+n)-.5,B={x:Ha(K+D)-.5,y:c,width:w+.5,height:u.h+C+.5,radius:0,fill:b.bgColor||Ma,ishot:!0,"stroke-dasharray":t,stroke:l,cursor:F?"pointer":
"","stroke-width":0},Z?Z.attr(B):(L.background=q.rect(N).attr(B).hover(J,aa),M={isHeader:b.isHeader,label:b.text,vAlign:b.vAlign,align:b.align,link:b.link,id:b.id},L.background.click(r).data("dataObj",b).data("eventArgs",M).data("data",{y:c,gridObj:b,rollOverColor:k,useHover:!0,useNext:!0,height:u.h+C+.5,hoverEle:T.items.hoverEle})),b.isNaN||(u=b.dimension,B=b.text,B=b.align,Z=L.label,B=b.text,Ta(B)&&""!==B&&($=b.style,m.setStyle($),G=m.getSmartText(B,w-8,fa(Sa($.lineHeight,10),u.h)),$.title=G.oriText,
B=b.align,B={text:G.text,ishot:!0,x:K+w*gb[B]+Va[B],y:x+u.h-u.h*tb[b.vAlign],"text-anchor":Ua[B],direction:d.textDirection,cursor:F?"pointer":"","vertical-align":b.vAlign},Z?Z.attr(B):L.label=q.text(N).attr(B).css($).hover(J,aa).click(r).data("eventArgs",M).data("dataObj",b).data("data",{y:c,gridObj:b,rollOverColor:k,useHover:!0,height:u.h+C+.5,useNext:!0,hoverEle:T.items.hoverEle}))),b.xPos=K,b.yPos=Ha(x+u.h)-s%2*.5,h.push("M",K,b.yPos,"h",w),(Z=L.hBorder)?Z.attr("path",h):L.hBorder=q.path(h,N).attr({"stroke-dasharray":t,
stroke:l,"stroke-width":s}),x+=u.h,b.nextCol||(D=C,n-=0,Z=b.first.items.vBorder,B=["M",Ha(K+w)-s%2*.5,y,"v",ea],Z?Z.attr("path",B):b.first.items.vBorder=q.path(B,p).attr({"stroke-dasharray":t,stroke:l,"stroke-width":s}),b.nextRow&&!b.isLast&&(b.first.items.dragEle||(b.first.items.dragEle=q.path(B,g.gridTracker).attr({stroke:d.gridResizeBarColor,"stroke-width":d.gridResizeBarThickness,visibility:"hidden"})),b.first.items.tracker||(b.first.items.tracker=q.path(B,g.gridTracker).attr({stroke:Ma,ishot:!0,
"stroke-width":30}).css("cursor",ka.svg&&"ew-resize"||"e-resize").drag(this.dragMove,this.dragStart,this.dragUp).data("drag-options",{grid:b.first,xPos:Ha(K+w)-s%2*.5,chart:a})))),b=b.nextCol},dragStart:function(){var b=this.data("drag-options"),a=b.grid,H=a.items,d=a.nextRow,e={style:{lineHeight:16}},k=a.nextCol.style||e,m=d&&d.nextCol&&d.nextCol.style||e,y=b.chart,f=y.canvasLeft,g=a.dimension,k=fa(Sa(a.style.lineHeight,10),Sa(k.lineHeight,10))+2,e=fa(Sa((d||e).style.lineHeight,10),Sa(m.lineHeight,
10))+2;b.leftSideLimit=f+c(a.dimension.x,0)+k;b.rightSideLimit=f+c(d&&d.dimension.x+d.dimension.w,g.x+g.w)-e;b.origX=b.lastX||(b.lastX=0);H.dragEle.show();y.trackerClicked=!0;b.draged=!1},dragMove:function(b){var a=this.data("drag-options"),c=a.grid.items,d=a.xPos+b,e=a.leftSideLimit,k=a.rightSideLimit;d<e&&(b=e-a.xPos);d>k&&(b=k-a.xPos);d={transform:"t"+(a.origX+b)+ic+0};this.attr(d);c.dragEle.attr(d);a.draged=!0;a.lastX=b},dragUp:function(){var b=this.data("drag-options"),a=b.chart,c=b.grid,d=c.nextRow,
e=a.canvasLeft,k=c.dimension,m=d&&d.dimension,y=c.items,f={hcJSON:{dataTable:{}}};a.trackerClicked=!1;y.dragEle.hide();b.draged&&(k.w=b.xPos+b.lastX-e-k.x,c.nextCol&&(c.nextCol.dimension.w=k.w),f.hcJSON.dataTable[c.key]={dimension:k},d&&(m.w+=m.x-k.x-k.w,m.x=k.x+k.w,d.dimension.w=m.w,d.dimension.x=m.x,a.drawProcess(d),f.hcJSON.dataTable[d.key]={dimension:m}),a.drawProcess(c),Qa(a.logic.chartInstance.jsVars._reflowData,f,!0),b.xPos+=b.lastX,b.lastX+=b.origX)},drawCategories:function(){var b=this,a=
b.options,e=a.chart,d=b.paper,q=b.layers,k=b.logic.smartLabel,m=b.canvasTop,y=a.categories,f=a.dataTable.processHeader,g=y.FCCAT_0_0,v=y.axis,p=y.endX,s=y.startX,C=p-s,l=e.ganttLineThickness,t=f.totalPH,D=[],n=[],h=q.dataset,q=q.ganttHeaderLayer,x,w,O,T,F,J,L,M,N,B,Z,G,$,K,u;$=function(a){Y.call(this,b,a,"CategoryClick")};K=function(a){na=clearTimeout(na);if(!W||W.removed)W=null;W&&b.gridOutHandler.call(W);b.gridHoverHandler.call(this);Y.call(this,b,a,"CategoryRollOver")};u=function(a){W=this;na=
clearTimeout(na);na=setTimeout(function(){b.gridOutHandler.call(W)},500);Y.call(W,b,a,"CategoryRollOut")};T=y.items||(y.items={});f=a.dataTable.processHeader;for(T.hoverEle=d.rect(0,m+f.dimension.h,50,f.totalPH-f.dimension.h,0,h).attr({fill:Ma,visibility:"hidden","stroke-width":0});g;)w=C/g.dimension.numCat,F=s+w*(g.index+1),N=F-w,M=g.dimension.h,B=N,G=m+g.dimension.y,J=g.align,L=g.vAlign,O=g.link,T=g.items||(g.items={}),w=!(!g.nextRow&&g.nextCol),Z=a.verticalScroll.enabled&&w?a.scrollOptions.height:
0,x={align:g.align,vAlign:g.vAlign,link:g.link,text:g.text},N=B=c(v.getPixel(g.start),N),F=c(v.getPixel(!w&&g.nextCol.start||(w?fa(g.end||0,a.max):void 0)),F),w=F-N,B=va(B)+.5,G=va(G)+.5,g.isLast&&(D.push("M",B,G,"v",t-g.dimension.y),G-=.5*l,M-=l,e.extendCategoryBg&&d.rect(B,G,w,t,0,h).attr({fill:g.bgColor,"stroke-width":0,stroke:e.ganttLineColor}).toBack()),T.background=d.rect(B,G,w+Z,M,0,q).attr({fill:g.bgColor,ishot:!0,"stroke-width":0,cursor:O?"pointer":"",stroke:e.ganttLineColor}).click($).data("eventArgs",
x).data("dataObj",g).hover(K,u).data("data",{x:B,width:w,gridObj:g,hoverEle:y.items.hoverEle}),n.push("M",B,G,"v",M),g.nextRow&&n.push("M",s,G+M,"H",p+Z),k.setStyle(g.style),F=k.getSmartText(g.text,w-5,M),g.style.title=F.oriText,T.label=d.text(q).attr({text:F.text,ishot:!0,x:B+w*gb[J]+Va[J],y:G+M-M*tb[L],"text-anchor":Ua[J],cursor:O?"pointer":"",direction:e.textDirection,"vertical-align":L}).css(g.style).hover(K,u).click($).data("eventArgs",x).data("dataObj",g).data("data",{x:B,width:w,gridObj:g,
hoverEle:y.items.hoverEle}),g=g.nextCol;for(;f;)D.push("M",y.startX,f.yPos,"H",p),f=f.nextCol;T=y.items||(y.items={});T.headerGrid=d.path(n,q).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":l,stroke:e.ganttLineColor});T.processGrid=d.path(D,h).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":e.ganttLineThickness,stroke:e.ganttLineColor})},drawScroller:function(){var b=this,a=b.options,e=b.paper,d=b.layers,q=b.canvasTop,k=b.canvasHeight,m=a.scrollOptions,y=a.categories,f=
y.startX,g=y.endX-f,v=m.flatScrollBars,p={hcJSON:{categories:{scroll:{}}}},s=d.dataset,C=d.datalabels,l=d.ganttTracker,t=d.ganttHeaderLayer,D=b.logic.chartInstance&&b.logic.chartInstance.jsVars._reflowData||{},n=a.chart,h=d.gridLayer,x=(f=a.dataTable)&&f.processHeader,w=b.canvasLeft,O=b.canvasWidth,J=n.gridBorderThickness,F=n.totalGridWidth,ea=Da(n.ganttStartX,F)+J,L=y.scroll,M=f&&f.__scrollOptions,N=a.verticalScroll,B={hcJSON:{dataTable:{__scrollOptions:{}},verticalScroll:{}}},Z=B.hcJSON.dataTable.__scrollOptions,
G=x.totalPH-x.dimension.h,$=d.gridHeaderLayer,K=d.gridTracker,u,r,f=c(y.startX,n.ganttStartX),d=d.scroll=d.scroll||e.group("scroll").insertAfter(l);L.enabled&&(a=y.visibleW/g,L.scroller=e.scroller(f,q+k-m.height,y.visibleW,m.height,!0,{showButtons:m.showButtons,displayStyleFlat:v,buttonWidth:m.buttonWidth,scrollRatio:a,scrollPosition:L.startPercent},d).attr({"scroll-display-style":v,fill:m.color}).scroll(function(a){r=-va(a*(g-y.visibleW));s&&s.transform(["T",r,s.data("vOffset")]);C&&C.transform(["T",
r,C.data("vOffset")]);l&&l.transform(["T",r,l.data("vOffset")]);t&&t.transform(["T",r,0]);s&&s.data("hOffset",r);C&&C.data("hOffset",r);l&&l.data("hOffset",r);p.hcJSON.categories.scroll.startPercent=a;Qa(D,p,!0)}),function(){var a;ka.eve.on("raphael.scroll.start."+L.scroller.id,function(c){a=c;V.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ka.eve.on("raphael.scroll.end."+L.scroller.id,function(c){V.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),
L.startPercent&&(r=-va(L.startPercent*(g-y.visibleW)),s&&s.data("hOffset",r),C&&C.data("hOffset",r),l&&l.data("hOffset",r),t&&t.transform(["T",r,0]),s&&s.transform(["T",r,s.data("vOffset")]),C&&C.transform(["T",r,s.data("vOffset")]),l&&l.transform(["T",r,s.data("vOffset")])));M.enabled&&(M.scroller=e.scroller(w,q+k-m.height,ea,m.height,!0,{showButtons:m.showButtons,displayStyleFlat:v,buttonWidth:m.buttonWidth,scrollRatio:ea/F,scrollPosition:M.startPercent},d).attr({"scroll-display-style":v,fill:m.color}).scroll(function(a){r=
-va(a*(F-ea));h&&h.transform(["T",r,h.data("vOffset")]);$&&$.transform(["T",r,0]);K&&K.transform(["T",r,K.data("vOffset")]);h.data("hOffset",r);$.data("hOffset",r);K.data("hOffset",r);Z.startPercent=a;Qa(D,B,!0)}),function(){var a;ka.eve.on("raphael.scroll.start."+M.scroller.id,function(c){a=c;V.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ka.eve.on("raphael.scroll.end."+M.scroller.id,function(c){V.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),
M.startPercent&&(r=-va(M.startPercent*(F-ea)),h&&h.transform(["T",r,0]),K&&K.transform(["T",r,0]),$&&$.transform(["T",r,0]),h.data("hOffset",r),K.data("hOffset",r)));N.enabled&&(u=n.processHeight-x.dimension.h,N.scroller=e.scroller(w+O-m.height,q+x.dimension.h,m.height,n.processHeight-x.dimension.h,!1,{showButtons:m.showButtons,displayStyleFlat:v,buttonWidth:m.buttonWidth,scrollRatio:u/G,scrollPosition:N.startPercent},d).attr({"scroll-display-style":v,fill:m.color}).scroll(function(a){r=-va(a*(G-
u));h&&h.transform(["T",h.data("hOffset"),r]);s&&s.transform(["T",s.data("hOffset"),r]);C&&C.transform(["T",C.data("hOffset"),r]);l&&l.transform(["T",l.data("hOffset"),r]);K&&K.transform(["T",K.data("hOffset"),r]);h.data("vOffset",r);K.data("vOffset",r);s.data("vOffset",r);l.data("vOffset",r);C.data("vOffset",r);B.hcJSON.verticalScroll.startPercent=a;Qa(D,B,!0)}),function(){var a;ka.eve.on("raphael.scroll.start."+N.scroller.id,function(c){a=c;V.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});
ka.eve.on("raphael.scroll.end."+N.scroller.id,function(c){V.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),N.startPercent&&(r=-va(N.startPercent*(G-u)),h&&h.transform(["T",h.data("hOffset"),r]),s&&s.transform(["T",s.data("hOffset"),r]),C&&C.transform(["T",C.data("hOffset"),r]),l&&l.transform(["T",l.data("hOffset"),r]),K&&K.transform(["T",K.data("hOffset"),r]),h.data("vOffset",r),K.data("vOffset",r),s.data("vOffset",r),C.data("vOffset",r),l.data("vOffset",
r)))},finalizeScrollPlots:function(){var b=this,a=b.options,c=b.canvasTop,d=a.categories,e=d.endX,k=d.startX,m=d.scroll,y=a.chart,f=a.dataTable,g=f&&f.processHeader,v=b.canvasLeft,p=y.gridBorderThickness,s=y.totalGridWidth,C=Da(y.ganttStartX,s)+p,l,t,D,n,h,x=e-k-d.visibleW,e=b.container,w=f&&f.__scrollOptions,O=a.verticalScroll,T=g.totalPH,F=y.processHeight-g.dimension.h,ea,L,M,N,B,m=d.scroll,a=function(a){var e=b.elements.canvas,f=N.left,p=N.top,q=a.type,r=sb&&J.getTouchEvent(a)||kc,f=a.layerX||
r.layerX||(a.pageX||r.pageX)-f;a=a.layerY||r.layerY||(a.pageY||r.pageY)-p;switch(q){case "dragstart":B=e.isPointInside(f,a);ea=f>k&&f<k+d.visibleW;M=f>v&&f<k+d.visibleW&&a>c+g.dimension.h;L=f<k;l=B&&f||null;t=B&&a||null;break;case "dragend":B=!1;h=n=D=t=l=void 0;break;default:if(!B||b.trackerClicked)break;e=f-l;q=a-t;l=f;t=a;ea&&m&&m.scroller&&(D=m.scroller.attrs["scroll-position"]-e/x,m.scroller.attr({"scroll-position":D}));M&&O&&O.scroller&&(n=O.scroller.attrs["scroll-position"]-q/(T-F),O.scroller.attr({"scroll-position":n}));
L&&w&&w.scroller&&(h=w.scroller.attrs["scroll-position"]-e/(s-C),w.scroller.attr({"scroll-position":h}))}};sb&&(N=J.getPosition(e),e&&(mc(e,"dragstart drag dragend",a),lc(e,"dragstart drag dragend",a)))},gridHoverHandler:function(){var b=this.data("data"),a=b.gridObj,c=!!a.prevRow,d={};if(!a.isHeader)if(b.x&&(d.x=b.x),b.y&&(d.y=b.y),b.width&&(d.width=b.width),b.height&&(d.height=b.height),a.hoverColor&&(d.fill=a.hoverColor),a.usePlotHover&&b.hoverEle.attr(d).show(),b.useNext&&a.useHover){for(;a&&
c;)a=a.prevRow,c=!!a.prevRow;for(;a;)a.items.background.attr("fill",a.hoverColor),a=a.nextRow}else a.useHover&&a.items.background.attr("fill",a.hoverColor)},gridOutHandler:function(){var b=this.data("data"),a=b.gridObj,c=!!a.prevRow;if(!a.isHeader)if(a.usePlotHover&&b.hoverEle.hide(),b.useNext&&a.useHover){for(;a&&c;)a=a.prevRow,c=!!a.prevRow;for(;a;)a.items.background.attr("fill",a.bgColor||Ma),a=a.nextRow}else a.useHover&&a.items.background.attr("fill",a.bgColor)},drawAxes:function(){if(this.options.dataTable){Pa["renderer.cartesian"].drawAxes.call(this,
arguments);var b=this.options,a=b.chart,e=this.paper,d=this.layers,q=d.layerBelowDataset,k=d.layerAboveDataset,m=d.gridLayer,y=d.dataset,f=b.dataTable,g=b.categories,f=f&&f.processHeader,v=this.canvasTop,y=this.canvasLeft,m=a.gridBorderThickness,p=Da(a.ganttStartX,a.totalGridWidth)+m,s=f.dimension,C=s.h,s=a.processHeight-s.h,l=c(g.startX,a.ganttStartX),g=g.visibleW,a=.5*a.ganttLineThickness,m=.5*m,m=d.gridLayer=d.gridLayer||e.group("grid",q).attr({"clip-rect":[y,v+C+m,p,s-m]});d.gridHeaderLayer=d.gridHeaderLayer||
e.group("grid-header",q).attr({"clip-rect":[y,v,p,C+s]});q=d.gridTracker=d.gridTracker||e.group("grid-tracker",q).attr({"clip-rect":[y,v,p,C+s]});m.data("vOffset",0);m.data("hOffset",0);q.data("vOffset",0);q.data("hOffset",0);d.ganttHeaderLayer=d.ganttHeaderLayer||e.group("gantt",k).attr({"clip-rect":[l,v,g+(b.verticalScroll.enabled?b.scrollOptions.height:0),this.chartHeight]});y=d.dataset.attr({"clip-rect":[l,v+C-a,g,s+a]});b=d.datalabels.attr({"clip-rect":[l,v+C-a-10,g,s+a+10]});e=d.ganttTracker=
e.group("gantt-hot",d.tracker).attr({"clip-rect":[l,v+C-a,g,s+a]});y.data("vOffset",0);y.data("hOffset",0);b.data("vOffset",0);b.data("hOffset",0);e.data("vOffset",0);for(e.data("hOffset",0);f;)this.drawProcess(f),f=f.nextRow;this.drawCategories()}},drawPlotGantt:function(b){var a=this,H=a.options,d=H.chart,q=a.paper,k=a.layers,m=b.data,y=b.items,f=m.length,g=k.dataset,v=k.datalabels,p=H.dataTable,s=p.processHeader,C=H.categories,l=C.axis,t=a.canvasTop,D=d.taskBarRoundRadius,f=H.plotOptions.series,
n=isNaN(+f.animation)&&f.animation.duration||1E3*f.animation,h=H.tasksMap||(H.tasksMap={}),x=H.milestone,w=H.trendlines,O=s.dimension.h,J=d.taskDatePadding,F,ea,L,M,N,B,Z,G,$,K,u,r,W,aa,ca,V,fa,A,R,ba,E;b.graphics=[];ca=g.shadows||(g.shadows=q.group("shadows",g));f=w&&w.length;for(b=0;b<f;b+=1)u=w[b],u.end||(u.end=u.start),u.end&&(R=l.getPixel(u.start),V=l.getPixel(u.end),ba=u.thickness,H=u.items||(u.items={}),F=void 0,u.isTrendZone?(K=["M",R+.5*(V-R),t+O,"v",t+s.totalPH],ba=V-R):(K=["M",R,t+O,"L",
V,t+O+s.totalPH],F=u.dashedStyle),H.trendLine=q.path(K,g).attr({stroke:u.color,"stroke-width":ba,"stroke-dasharray":F}),Ta(u.displayValue)&&""!==u.displayValue&&(H.label=q.text(k.ganttHeaderLayer).attr({text:u.displayValue,direction:d.textDirection,x:K[1],y:0}).css(u.style),F=H.label._getBBox().height,u=t+d.processHeight+(!C.scroll.enabled||d.marginBottom<F?.5*F:-(.5*F)-5),H.label.attr("y",u)));v.hide();k=function(){v.show()};w=s=function(b){Y.call(this,a,b)};C=function(b){Y.call(this,a,b,"DataPlotRollOver")};
t=function(b){Y.call(this,a,b,"DataPlotRollOut")};O=function(b){b&&b.click(function(b){Y.call(this,a,b)}).hover(function(b){var c=this.data("dataObj");Y.call(this,a,b,"DataPlotRollOver");c.showHoverEffect&&a.taskHoverHandler.call(this,a)},function(b){var c=this.data("dataObj");Y.call(this,a,b,"DataPlotRollOut");c.showHoverEffect&&a.taskHoverOutHandler.call(this,a)}).data("dataObj",A).data("eventArgs",ea)};f=m.length;for(b=0;b<f;b+=1)A=m[b],H=A.processId,u=p[H],V=fa=A.color,H=A.items||(A.items={}),
K=A.animation?n||1E3:0,u&&(E=A.borderThickness,R=va(l.getPixel(A.start)),ba=ac(M=l.getPixel(A.end)-R),R&&ba&&(L=u.dimension.h,u=u.yPos-L,F=L*(/%/g.test(A.height)&&.01*Gb(A.height,10))||c(A.height,L),r=L*(/%/g.test(A.topPadding)&&.01*Gb(A.topPadding,10))||c(A.topPadding,L),u+=Da(r,L-F),aa=.5*F,W=A.toolText,r=A.link,(L=y[b])||(L=y[b]={index:b,dataLabel:null,start:A.start,end:A.end,startLabel:null,endLabel:null,tracker:null}),A.index=b,N=e(A.id,b),""!==N&&h[N]&&(h[N].items=L,h[N].x=R,h[N].y=u,h[N].h=
F,h[N].w=ba),M=N=B=Z=G=$=null,A.showAsGroup?(K?(M=q.path(["M",R,u],g),M.animate({path:["M",R,u,"v",F,"L",R+aa,u+aa,"H",R+ba-aa,"L",R+ba,u+F,"v",-F,"H",R]},K,"normal",k)):(M=q.path(["M",R,u,"v",F,"L",R+aa,u+aa,"H",R+ba-aa,"L",R+ba,u+F,"v",-F,"H",R],g),k&&k()),M.attr({fill:V,stroke:A.borderColor,cursor:r?"pointer":"",ishot:!0,"stroke-width":A.borderThickness}).tooltip(W).shadow(d.shadow&&A.shadow,ca)):(-1!==A.percentComplete&&(M=ba*A.percentComplete*.01,V=Ma,N=H.taskFill=q.rect(R,u,0,F,0,g).attr({fill:fa,
cursor:r?"pointer":"",ishot:!0,"stroke-width":0,width:K?0:M||1}).tooltip(W),K&&N.animate({width:M||1},K,"normal"),B=q.rect(R,u,0,F,0,g).attr({fill:A.slackColor,cursor:r?"pointer":"",ishot:!0,"stroke-width":0,x:K?R:R+M||1,width:K?0:ba-M||1}).tooltip(W),K&&B.animate({x:R+M||1,width:ba-M||1},K,"normal")),H=ka.crispBound(R,u,ba,F,E),M=q.rect(H.x,H.y,0,H.height,D,g).attr({fill:V,stroke:A.borderColor,cursor:r?"pointer":"",ishot:!0,"stroke-width":A.borderThickness,width:K?0:H.width||1}).tooltip(W).shadow(d.shadow&&
A.shadow,ca),K?M.animate({width:H.width||1},K,"normal",k):k&&k()),Ta(A.label)&&""!==A.label&&(H=A.labelAlign,Z=q.text().attr({text:A.label,x:R+ba*gb[H]+Va[H],"text-anchor":Ua[H],direction:d.textDirection,cursor:r?"pointer":"",ishot:!0,y:u-.5*Sa(A.style.lineHeight,10)-d.taskLabelPadding}).css(A.style),v.appendChild(Z)),Ta(A.startDate)&&""!==A.startDate&&(G=q.text().attr({text:A.startDate,x:R-2-J,y:u+.5*F,cursor:r?"pointer":"",ishot:!0,direction:d.textDirection,"text-anchor":"end"}).css(A.style),v.appendChild(G)),
Ta(A.endDate)&&""!==A.endDate&&($=q.text().attr({text:A.endDate,x:R+ba+2+J,y:u+.5*F,cursor:r?"pointer":"",ishot:!0,direction:d.textDirection,"text-anchor":"start"}).css(A.style),v.appendChild($)),L.graphic=M,L.percentCompleteGraphic=N,L.slackGraphic=B,L.dataLabel=Z,L.startLabel=G,L.endLabel=$,ea={processId:A.processId,taskId:A.id,start:A._start,end:A._end,showAsGroup:A.showAsGroup,link:A.link,sourceType:"task",percentComplete:-1!==A.percentComplete&&A.percentComplete},N&&N.click(s).hover(C,t).data("eventArgs",
ea),B&&B.click(w).data("eventArgs",ea),Ra([M,Z,G,$],O)));p=function(b){Y.call(this,a,b,"MilestoneClick")};D=function(b){var c=this.data("dataObj");Y.call(this,a,b,"MilestoneRollOver");c.showHoverEffect&&c.items.graphic.attr({fill:c.hoverFillColor,stroke:c.hoverBorderColor,"fill-opacity":c.hoverFillAlpha,"stroke-opacity":c.hoverBorderAlpha})};J=function(b){var c=this.data("dataObj");Y.call(this,a,b,"MilestoneRollOut");c.showHoverEffect&&c.items.graphic.attr({fill:c.fillColor,stroke:c.borderColor,"fill-opacity":c.fillAlpha,
"stroke-opacity":c.borderAlpha})};this.drawConnectors();H=null;f=x&&x.length;for(b=0;b<f;b+=1)m=x[b],u=h[m.taskId],H=m.items||(m.items={}),u&&(y=ka.animation({"fill-opacity":m.fillAlpha,"stroke-opacity":m.borderAlpha},n,"normal"),ea={sides:m.sides,date:m.origDate,radius:m.radius,taskId:m.taskId,toolText:m.toolText,link:m.link,numSides:m.numSides},H.graphic=q.polypath(m.numSides,l.getPixel(m.date.ms),u.y+.5*u.h,c(m.radius,.6*u.h),m.startAngle,m.depth,g).attr({fill:m.fillColor,"fill-opacity":n?0:m.fillAlpha,
stroke:m.borderColor,"stroke-opacity":n?0:m.borderAlpha,groupId:"gId"+b,ishot:!0,cursor:m.link?"pointer":"","stroke-width":m.borderThickness}).tooltip(m.toolText).click(p).data("eventArgs",ea).data("dataObj",m),H.label=q.text().attr({text:m.displayValue,x:l.getPixel(m.date.ms),y:u.y+.5*u.h,groupId:"gId"+b,cursor:m.link?"pointer":"",ishot:!0,direction:d.textDirection,"text-anchor":"middle"}).css(m.style).tooltip(m.toolText).click(p).data("eventArgs",ea).data("dataObj",m),v.appendChild(H.label),n&&
H.graphic.animate(y.delay(n)),H.graphic.hover(D,J),H.label.hover(D,J))},taskHoverOutHandler:function(b){var a=b.options.tasksMap;b=this.data("dataObj");var a=a[e(b.id,b.index)].items,c={fill:b.color,stroke:b.borderColor,"stroke-width":b.borderThickness,"stroke-dasharray":b.dashedStyle};-1===b.percentComplete||b.showAsGroup||(a.slackGraphic.attr({fill:b.slackColor}),a.percentCompleteGraphic.attr({fill:b.color}),delete c.fill);a.graphic.attr(c)},taskHoverHandler:function(b){var a=b.options.tasksMap;
b=this.data("dataObj");var a=a[e(b.id,b.index)].items,c={fill:b.hoverFillColor,stroke:b.hoverBorderColor};-1===b.percentComplete||b.showAsGroup||(a.slackGraphic.attr({fill:b.slackHoverColor}),a.percentCompleteGraphic.attr({fill:b.hoverFillColor}),delete c.fill);a.graphic.attr(c)},drawConnectors:function(){var b=this,a=b.paper,c=b.options,d=c.chart.connectorExtension,e=c.connectors,k=c.tasksMap,m=e.length,y=b.layers.dataset,f=[],c=c.plotOptions.series,c=isNaN(+c.animation)&&c.animation.duration||1E3*
c.animation,g,v,p,s,C,l,t,D,n,h,x,w,J,T,F;J=function(a){Y.call(this,b,a,"ConnectorClick")};T=function(a){var c=this.data("dataObj"),d=k[c.fromTaskId],e=k[c.toTaskId],f={stroke:c.hoverColor,"stroke-dasharray":c.dashedStyle,"stroke-width":c.hoverThickness};Y.call(this,b,a,"ConnectorRollOver");c.showHoverEffect&&(Ra([d,e],function(a){var b={fill:a.dataObj.hoverFillColor,stroke:a.dataObj.hoverBorderColor};-1===a.dataObj.percentComplete||a.dataObj.showAsGroup||(a.items.slackGraphic.attr({fill:a.dataObj.slackHoverColor}),
a.items.percentCompleteGraphic.attr({fill:a.dataObj.hoverFillColor,stroke:a.dataObj.hoverBorderColor}),delete b.fill);a.items.graphic.attr(b)}),c.items.connector.attr(f))};F=function(a){var c=this.data("dataObj"),d=k[c.fromTaskId],e=k[c.toTaskId],f={stroke:c.color,"stroke-width":c.thickness,"stroke-dasharray":c.dashedStyle};Y.call(this,b,a,"ConnectorRollOut");c.showHoverEffect&&(Ra([d,e],function(a){var b={fill:a.dataObj.color,stroke:a.dataObj.borderColor,"stroke-width":a.dataObj.borderThickness,
"stroke-dasharray":a.dataObj.dashedStyle};-1===a.dataObj.percentComplete||a.dataObj.showAsGroup||(a.items.slackGraphic.attr({fill:a.dataObj.slackColor}),a.items.percentCompleteGraphic.attr({fill:a.dataObj.color}),delete b.fill);a.items.graphic.attr(b)}),c.items.connector.attr(f))};for(g=0;g<=m;g+=1)if(p=e[g]||{},l=p.fromTaskId,s=p.toTaskId,v=k[l],n=k[s],s=p.items||(p.items={}),v&&n){h=v.y+.5*v.h;x=n.y+.5*n.h;C=h==x;l=v.x;t=v.x+v.w;D=n.x;n=n.x+n.w;w=w=0;0===p.fromTaskConnectStart&&1===p.toTaskConnectStart&&
(w=1);0===p.fromTaskConnectStart&&0===p.toTaskConnectStart&&(w=2);1===p.fromTaskConnectStart&&1===p.toTaskConnectStart&&(w=3);1===p.fromTaskConnectStart&&0===p.toTaskConnectStart&&(w=4);if(C)switch(v=v.height,w){case 1:w=(D-t)/10;f=["M",t,h,t+w,h,"L",t+w,h,t+w,h-v,"L",t+w,h-v,D-w,h-v,"L",D-w,h-v,D-w,h,"L",D-w,h,D,x,"L",n+d,x,n,x];break;case 2:f=["M",t,h,t+d,h,"L",t+d,h,t+d,h-v,"L",t+d,h-v,n+d,h-v,"L",n+d,x-v,n+d,x];break;case 3:f=["M",l,h,l-d,h,"L",l-d,h,l-d,h-v,"L",l-d,h-v,D-d,h-v,"L",D-d,h-v,D-
d,h,"L",D-d,h,D,h];break;case 4:f=["M",l,h,l-d,h,"L",l-d,h,l-d,h-v,"L",l-d,h-v,n+d,h-v,"L",n+d,h-v,n+d,h,"L",n+d,h,n,h]}else switch(w){case 1:f=["M",t,h,t+(D-t)/2,h,"L",t+(D-t)/2,h,t+(D-t)/2,x,"L",t+(D-t)/2,x,D,x];f=t<=D?["M",t,h,t+(D-t)/2,h,"L",t+(D-t)/2,h,t+(D-t)/2,x,"L",t+(D-t)/2,x,D,x]:["M",t,h,t+d,h,"L",t+d,h,t+d,h+(x-h)/2,"L",t+d,h+(x-h)/2,D-d,h+(x-h)/2,"L",D-d,h+(x-h)/2,D-d,x,"L",D-d,x,D,x];break;case 2:w=0>n-t?0:n-t;f=["M",t,h,t+d+w,h,"L",t+d+w,h,t+d+w,x,"L",t+d+w,x,n,x];break;case 3:w=0>
l-D?0:l-D;f=["M",l,h,l-d-w,h,"L",l-d-w,h,l-d-w,x,"L",l-d-w,x,D,x];break;case 4:f=l>n?["M",l,h,l-(l-n)/2,h,"L",l-(l-n)/2,h,l-(l-n)/2,x,"L",l-(l-n)/2,x,n,x]:["M",l,h,l-d,h,"L",l-d,h,l-d,h+(x-h)/2,"L",l-d,h+(x-h)/2,n+d,h+(x-h)/2,"L",n+d,h+(x-h)/2,n+d,x,"L",n+d,x,n,x]}s.connector?s.connector.animate({path:f}):(l=ka.animation({"stroke-opacity":p.alpha},c,"normal"),s.connector=a.path(f,y).attr({stroke:p.color,"stroke-opacity":0,"stroke-width":p.thickness,"stroke-dasharray":p.dashedStyle}).animate(l.delay(c)));
l={fromTaskId:p.fromTaskId,toTaskId:p.toTaskId,fromTaskConnectStart:p.fromTaskConnectStart,toTaskConnectStart:p.toTaskConnectStart,link:p.link,sourceType:"connector"};s.tracker=a.path(f,y).attr({stroke:Ma,"stroke-width":fa(p.thickness,10),ishot:!0,cursor:p.link?"pointer":""}).data("dataObj",p).data("eventArgs",l).click(J);s.tracker.hover(T,F)}}},Pa["renderer.cartesian"])}]);
